#!/usr/bin/env python3
"""Writes docs/operations/RELEASE_MAP.md from a built database (audit T3-06): what each release brings into production,
who owns it, what it depends on, the switches that open it, and how a closed phase stays closed.

    python3 db/tools/release_map.py <database> [psql connection args...]

The phase of every table comes from sys.table_phase and the switches from sys.project_phase, so the map cannot drift
from the schema; rerun it after every schema change (it is part of the document regeneration).
"""
import json
import os
import subprocess
import sys
from collections import Counter, defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "docs", "operations", "RELEASE_MAP.md")

# Owning team of each schema: the team that answers for its data, migrations and on-call (named roles, not people)
OWNERS = {
    "iam": "Identity and access", "sec": "Security", "audit": "Security", "gov": "Security", "ref": "Platform core",
    "sys": "Platform core", "net": "Network and timetables", "ops": "Operations", "fleet": "Operations",
    "sales": "Booking", "pricing": "Booking", "fin": "Payments and finance", "acct": "Payments and finance",
    "bill": "Payments and finance", "rpt": "Data and reports", "crm": "Customer care", "brd": "Government integration",
    "ship": "Logistics", "frt": "Logistics", "ptn": "Partners", "rail": "Rail", "taxi": "Mobility services",
    "rent": "Mobility services", "ctr": "Contracted transport", "sch": "School transport", "gis": "Platform core",
}
# What a release needs outside the database
EXTERNAL = {
    "1A": "payment provider (card or e-wallet), SMS gateway, SMTP relay, through the egress proxy; ClamAV",
    "1B": "the 1A services; bank transfer files; partner webhooks through the egress proxy; key service (Vault or cloud KMS)",
    "ERP": "the carrier's accounting system (connectors)", "5": "government e-services (e-government infrastructure)",
    "6": "border authority systems", "7": "contracted GPS devices, station gates and screens",
    "SCH": "the Ministry of Education's licence registry when it exists", "CS": "telephony provider, AI model provider",
}
# Workers and jobs each release runs
WORKERS = {
    "1A": "outbox worker (notifications), file scanner, daily upkeep (partitions, purge, orphans, reconciliation)",
    "1B": "webhook delivery, scheduled reports, payment expiry, break-glass upkeep, egress allowlist, payment reconciliation",
}


def q(db, args, sql):
    return subprocess.run(["psql", *args, "-d", db, "-At", "-c", sql], check=True, capture_output=True, text=True).stdout


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    db, args = sys.argv[1], sys.argv[2:]
    phases = json.loads(q(db, args, """SELECT json_agg(json_build_object('code', code, 'name', name, 'switches', feature_keys,
                                          'scope', scope) ORDER BY ordinal) FROM sys.project_phase"""))
    tables = json.loads(q(db, args, "SELECT json_agg(json_build_object('t', table_name, 'p', phase_code, 'm', module)) FROM sys.table_phase"))
    gated = set(q(db, args, "SELECT schemaname || '.' || tablename FROM pg_policies WHERE policyname = 'phase_gate'").split())
    by_phase = defaultdict(list)
    for t in tables:
        by_phase[t["p"]].append(t["t"])
    lines = ["# Release map", "",
             "Generated by `db/tools/release_map.py` from the built database (audit T3-06); do not edit by hand.", "",
             "**What goes to production.** The whole schema is installed in every environment, so upgrades stay linear and "
             "tested. A release goes into **service** only when its switches are on:",
             "- **Tables:** every table of a phase whose switches are off is closed by a restrictive `phase_gate` policy, so "
             "no company can read or write it.",
             "- **Application:** the endpoints of a switched-off module answer 404.",
             "- **Workers:** they act only on rows that exist, and a closed phase has none.", "",
             "**Launch scope:** releases **1A** and **1B**. Every later phase stays switched off until it passes its own "
             "acceptance gate (security, privacy, capacity, recovery, runbooks).", "",
             "| Release | Switches | Tables | Owners (tables) | External services | Workers and jobs |",
             "|---|---|---|---|---|---|"]
    for p in phases:
        ts = sorted(by_phase.get(p["code"], []))
        owners = Counter(OWNERS.get(t.split(".")[0], "Platform core") for t in ts)
        own = ", ".join(f"{k} ({v})" for k, v in owners.most_common())
        sw = ", ".join(p["switches"]) or "always on"
        lines.append(f"| **{p['code']}** {p['name'].split(': ', 1)[-1]} | {sw} | {len(ts)} | {own} | {EXTERNAL.get(p['code'], 'none')} | "
                     f"{WORKERS.get(p['code'], 'shared workers only')} |")
    lines += ["", "## Closed until switched on", "",
              f"{len(gated)} tables carry a `phase_gate` policy. Tests that prove a closed phase stays closed:",
              "- **Database:** `db/tests/run_tests.sql`, audit R-14. Every table of a switched-off phase is closed, and a "
              "company reads and writes nothing of it.",
              "- **Application:** the module framework tests (`backend/tests/test_modules.py`). A switched-off module's "
              "endpoints answer 404.", "",
              "## Releases 1A and 1B in detail", ""]
    for code in ("1A", "1B"):
        ts = sorted(by_phase.get(code, []))
        lines.append(f"### {code} ({len(ts)} tables)")
        lines.append("")
        for schema, group in sorted(Counter(t.split(".")[0] for t in ts).items()):
            names = ", ".join(t.split(".")[1] for t in ts if t.startswith(schema + "."))
            lines.append(f"- **{schema}** ({OWNERS.get(schema, 'Platform core')}, {group}): {names}")
        lines.append("")
    lines += ["## Ownership", "",
              "Each owning team answers for its schemas' data, migrations (with the plan in `docs/database/MIGRATION_PLANS.md`), "
              "alerts and on-call. Changes that cross two teams' schemas need both teams' review. The two-way dependencies "
              "between schemas are frozen by test H-07: a new one fails the build.", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"written {OUT}: {len(phases)} releases, {len(tables)} tables, {len(gated)} gated")


if __name__ == "__main__":
    main()
