#!/usr/bin/env python3
"""Dependencies between modules (schemas) and reference cycles between tables, checked against an accepted baseline
(architecture review of design 3.9, October 2026; docs/database/ARCHITECTURE_REVIEW_RESPONSE.md).

Schemas are modules of one database, not separate services: a foreign key between two of them is allowed in either
direction. What this tool stops is growth without a decision. It fails when the built database has
* a pair of schemas that reference each other in both directions and is not in the baseline, or
* a cycle of foreign keys between tables that is not in the baseline,
and it reports baseline entries that no longer exist (remove them, the count only goes down).

    python3 db/tools/schema_dependencies.py <database> [--write-doc] [psql connection args...]

--write-doc regenerates docs/database/SCHEMA_DEPENDENCIES.md (the module map with every cross-schema reference).
The baseline is db/schema_dependencies.json; an entry is added only with the reason, in the same change as the schema
file that needs it.
"""
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE = ROOT / "db" / "schema_dependencies.json"
DOC = ROOT / "docs" / "database" / "SCHEMA_DEPENDENCIES.md"
MAX_CYCLE = 6

EDGES_SQL = """
SELECT json_agg(json_build_object('from', s.oid::regclass::text, 'to', t.oid::regclass::text,
                                  'from_schema', sn.nspname, 'to_schema', tn.nspname,
                                  'columns', (SELECT string_agg(attname, ',' ORDER BY attnum) FROM pg_attribute
                                               WHERE attrelid = k.conrelid AND attnum = ANY (k.conkey)),
                                  'nullable', (SELECT bool_and(NOT attnotnull) FROM pg_attribute
                                                WHERE attrelid = k.conrelid AND attnum = ANY (k.conkey)))
                ORDER BY s.oid::regclass::text, k.conname)
  FROM pg_constraint k
  JOIN pg_class s ON s.oid = k.conrelid JOIN pg_namespace sn ON sn.oid = s.relnamespace
  JOIN pg_class t ON t.oid = k.confrelid JOIN pg_namespace tn ON tn.oid = t.relnamespace
 WHERE k.contype = 'f' AND NOT s.relispartition AND k.conparentid = 0 AND sn.nspname NOT IN ('pg_catalog', 'information_schema')
"""


def fetch_edges(db, args):
    out = subprocess.run(["psql", *args, "-d", db, "-At", "-v", "ON_ERROR_STOP=1", "-c", EDGES_SQL],
                         check=True, capture_output=True, text=True).stdout.strip()
    return json.loads(out or "[]")


def two_way_pairs(edges):
    direct = {(e["from_schema"], e["to_schema"]) for e in edges if e["from_schema"] != e["to_schema"]}
    return sorted({f"{min(a, b)}<->{max(a, b)}" for a, b in direct if (b, a) in direct})


def table_cycles(edges):
    """Elementary cycles of length 2..MAX_CYCLE between distinct tables, each named by its sorted member list."""
    graph = defaultdict(set)
    for e in edges:
        if e["from"] != e["to"]:
            graph[e["from"]].add(e["to"])
    found = set()
    for start in sorted(graph):
        stack = [(start, [start])]
        while stack:
            node, path = stack.pop()
            for nxt in graph[node]:
                if nxt == start and len(path) > 1:
                    found.add(",".join(sorted(path)))
                elif nxt not in path and nxt > start and len(path) < MAX_CYCLE:
                    stack.append((nxt, path + [nxt]))
    return sorted(found)


def write_doc(edges, pairs, cycles, baseline):
    by_pair = defaultdict(list)
    for e in edges:
        if e["from_schema"] != e["to_schema"]:
            by_pair[(e["from_schema"], e["to_schema"])].append(e)
    schemas = sorted({e["from_schema"] for e in edges} | {e["to_schema"] for e in edges})
    lines = [
        "# Module dependencies (generated)",
        "",
        "Generated by `db/tools/schema_dependencies.py --write-doc` from the built database. Do not edit by hand.",
        "",
        "**What this map is for:**",
        "- **Modules:** schemas are the modules of one PostgreSQL database. A foreign key keeps the reference true at",
        "  every commit, whichever direction it points.",
        "- **What is controlled:** growth. A new pair of schemas referring to each other, or a new cycle of references",
        "  between tables, fails CI unless it is added to `db/schema_dependencies.json` with its reason.",
        "- **Why:** see `ARCHITECTURE_REVIEW_RESPONSE.md`.",
        "",
        f"**Totals:** {len(schemas)} schemas, {sum(len(v) for v in by_pair.values())} cross-schema references, "
        f"{len(pairs)} two-way schema pairs, {len(cycles)} table cycles.",
        "",
        "## Two-way schema pairs",
        "",
        "| Pair | Accepted because | References each way |",
        "|---|---|---|",
    ]
    for p in pairs:
        a, b = p.split("<->")
        lines.append(f"| `{p}` | {baseline['schema_pairs'].get(p, '**not in the baseline**')} | "
                     f"{a}→{b}: {len(by_pair[(a, b)])}; {b}→{a}: {len(by_pair[(b, a)])} |")
    lines += ["", "## Cycles between tables", "",
              "Every cycle has at least one nullable link, so rows are inserted first and linked after. A cycle is not a "
              "deadlock path by itself: deadlocks come from the order in which transactions lock rows, which the load "
              "tests measure.", "",
              "| Tables | Accepted because |", "|---|---|"]
    for c in cycles:
        lines.append(f"| `{c.replace(',', '`, `')}` | {baseline['table_cycles'].get(c, '**not in the baseline**')} |")
    lines += ["", "## Every cross-schema reference", ""]
    for a, b in sorted(by_pair):
        lines.append(f"**{a} → {b}** ({len(by_pair[(a, b)])})")
        lines.append("")
        for e in by_pair[(a, b)]:
            lines.append(f"- `{e['from']}.{e['columns']}` → `{e['to']}`{'' if e['nullable'] else ' (required)'}")
        lines.append("")
    DOC.write_text("\n".join(lines))
    print(f"written {DOC.relative_to(ROOT)}")


def main():
    argv = sys.argv[1:]
    write = "--write-doc" in argv
    argv = [a for a in argv if a != "--write-doc"]
    if not argv:
        sys.exit(__doc__)
    db, args = argv[0], argv[1:]
    edges = fetch_edges(db, args)
    pairs, cycles = two_way_pairs(edges), table_cycles(edges)
    baseline = json.loads(BASELINE.read_text())
    new_pairs = [p for p in pairs if p not in baseline["schema_pairs"]]
    new_cycles = [c for c in cycles if c not in baseline["table_cycles"]]
    gone = [p for p in baseline["schema_pairs"] if p not in pairs] + [c for c in baseline["table_cycles"] if c not in cycles]
    if write:
        write_doc(edges, pairs, cycles, baseline)
    print(f"{len(pairs)} two-way schema pairs, {len(cycles)} table cycles (baseline {len(baseline['schema_pairs'])} and "
          f"{len(baseline['table_cycles'])})")
    for p in new_pairs:
        print(f"NEW two-way schema pair: {p}")
    for c in new_cycles:
        print(f"NEW table cycle: {c}")
    for g in gone:
        print(f"no longer present, remove from the baseline: {g}")
    if new_pairs or new_cycles:
        print("Point the new reference one way, or add it to db/schema_dependencies.json with the reason.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
