"""Carrier billing (5.11), service partners (14.11), loyalty partners and campaigns (5.12, 5.13), channels (14.7),
accounting operations (13.7), the contact center (7.11) and government adapters (phase 5)."""
from ._base import AG, Action, P, O, PA, Resource, c, retire, suspend, resume

RESOURCES = [
    # ------------------------------------------------------------- carrier billing
    Resource("plan", "carrier_billing", "bill.plan",
             c("code kind name annual_fee currency included_users extra_user_fee included_invoices included_api_calls commission_bp status"),
             c("code kind name annual_fee currency included_users extra_user_fee max_extra_users included_invoices included_api_calls "
               "included_whatsapp commission_bp overage_invoice_fee overage_api_per_1000 overage_whatsapp_fee self_service"),
             {P: "billing.manage", O: None, AG: None}, readonly_portals=(O, AG), group="billing", actions=(retire(),)),
    Resource("carrier-agreement", "carrier_billing", "bill.carrier_agreement", c("company_id label valid_days status created_at"),
             c("company_id label terms valid_days"), {P: "billing.manage", O: None, AG: None}, readonly_portals=(O, AG),
             creator_col="created_by", group="billing",
             actions=(Action("approve", {"status": "ACTIVE"}, {"status": ["PENDING"]}, four_eyes=("created_by", "approved_by")),
                      Action("reject", {"status": "REJECTED"}, {"status": ["PENDING"]}),
                      Action("end", {"status": "ENDED"}, {"status": ["ACTIVE"]}))),
    Resource("company-subscription", "carrier_billing", "bill.company_subscription",
             c("company_id source plan_id agreement_id status starts_at ends_at"), (),
             {P: "billing.manage", O: None, AG: None}, create=False, update=False, group="billing",
             actions=(Action("suspend", {"status": "SUSPENDED"}, {"status": ["ACTIVE", "GRACE"]}, portals=(P,)),
                      Action("resume", {"status": "ACTIVE"}, {"status": ["SUSPENDED", "GRACE"]}, portals=(P,)),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PENDING", "ACTIVE", "GRACE", "SUSPENDED"]}, portals=(P,)))),
    Resource("usage-event", "carrier_billing", "bill.usage_event", c("company_id kind qty ref_type ts"), (),
             {P: "billing.manage", O: None, AG: None}, create=False, update=False, order="ts DESC", group="billing"),
    Resource("carrier-invoice", "carrier_billing", "bill.carrier_invoice",
             c("uid company_id kind period_start period_end subtotal discount tax total currency status"), (),
             {P: "billing.manage", O: None, AG: None}, create=False, update=False, group="billing",
             actions=(Action("void", {"status": "VOID"}, {"status": ["DRAFT", "DUE"]}, portals=(P,)),)),
    Resource("carrier-invoice-line", "carrier_billing", "bill.carrier_invoice_line", c("invoice_id line_no kind description qty unit_price amount"), (),
             {P: "billing.manage", O: None, AG: None}, create=False, update=False, order="invoice_id DESC, line_no", group="billing"),

    # ------------------------------------------------------------- service partners
    Resource("partner", "service_partners", "ptn.partner",
             c("code party_id company_id partner_type station_id license_no license_expiry menu_enabled preorder_enabled compliance_state status"),
             c("code party_id company_id partner_type station_id lat lng geofence_m license_no license_expiry hours menu_enabled "
               "preorder_enabled avg_service_min"), {P: "partners.manage", O: None, PA: None}, readonly_portals=(O, PA),
             group="partners", actions=(Action("activate", {"status": "ACTIVE"}, {"status": ["PENDING", "SUSPENDED"]}), suspend(),
                                        Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("partner-contract", "service_partners", "ptn.partner_contract",
             c("partner_id version commission_model rate_bp fixed_fee carrier_fee carrier_share_pct settlement_cycle valid status"),
             c("partner_id version commission_model rate_bp fixed_fee tiers carrier_fee carrier_share_pct currency settlement_cycle credit_terms valid"),
             {P: "partners.manage", O: None}, readonly_portals=(O,), creator_col="created_by", group="partners",
             actions=(Action("submit", {"status": "PENDING_APPROVAL"}, {"status": ["DRAFT"]}),
                      Action("approve", {"status": "ACTIVE"}, {"status": ["PENDING_APPROVAL"]}, four_eyes=("created_by", "approved_by")),
                      Action("end", {"status": "ENDED"}, {"status": ["ACTIVE"]}))),
    Resource("station-employee", "service_partners", "ptn.station_employee", c("partner_id user_id role status"),
             c("partner_id user_id role"), {P: "partners.manage", O: "partners.operate"}, group="station",
             actions=(Action("disable", {"status": "DISABLED"}, {"status": ["ACTIVE"]}),
                      Action("enable", {"status": "ACTIVE"}, {"status": ["DISABLED"]}))),
    Resource("fuel-price", "service_partners", "ptn.fuel_price", c("partner_id fuel_type unit_price currency valid_from"),
             c("partner_id fuel_type unit_price currency valid_from"), {P: "partners.manage", O: None, PA: None},
             readonly_portals=(PA,), order="valid_from DESC", group="station"),
    Resource("fuel-card", "service_partners", "ptn.fuel_card",
             c("uid vehicle_id driver_party_id daily_limit monthly_limit currency fuel_types status"),
             c("vehicle_id driver_party_id daily_limit monthly_limit currency fuel_types"), {P: "partners.manage", O: None},
             company_col="company_id", group="fleet-fuel",
             actions=(Action("block", {"status": "BLOCKED"}, {"status": ["ACTIVE"]}),
                      Action("unblock", {"status": "ACTIVE"}, {"status": ["BLOCKED"]}), retire(("ACTIVE", "BLOCKED")))),
    Resource("fuel-session", "service_partners", "ptn.fuel_session",
             c("partner_id pump_ref station_employee_id company_id vehicle_id driver_party_id trip_id opened_at closed_at status"), (),
             {P: "partners.manage", O: None}, create=False, update=False, order="opened_at DESC", group="station"),
    Resource("odometer", "service_partners", "ptn.odometer_reading", c("vehicle_id session_id value_km ocr_value source driver_confirmed employee_confirmed ts"), (),
             {P: "partners.manage", O: None}, create=False, update=False, order="ts DESC", group="fleet-fuel"),
    Resource("fuel-anomaly", "service_partners", "ptn.fuel_anomaly",
             c("session_id anomaly_type severity distance_odometer_km distance_gps_km liters status resolved_at"), (),
             {P: "partners.manage", O: None}, create=False, update=False, group="fleet-fuel",
             actions=(Action("explained", {"status": "EXPLAINED"}, {"status": ["OPEN"]}, stamp="resolved_at", by="resolved_by"),
                      Action("confirm", {"status": "CONFIRMED"}, {"status": ["OPEN"]}, stamp="resolved_at", by="resolved_by", portals=(P,)),
                      Action("dismiss", {"status": "DISMISSED"}, {"status": ["OPEN"]}, stamp="resolved_at", by="resolved_by", portals=(P,)))),
    Resource("menu-item", "service_partners", "ptn.partner_menu_item", c("partner_id name category price currency available"),
             c("partner_id name category price currency available"), {P: "partners.manage", O: "partners.operate", PA: None},
             readonly_portals=(PA,), delete=True, group="station"),
    Resource("partner-order", "service_partners", "ptn.partner_order", c("uid partner_id user_id trip_id amount currency pickup_eta status created_at"), (),
             {P: "partners.manage", O: None, PA: None}, create=False, update=False, group="station",
             actions=(Action("accept", {"status": "ACCEPTED"}, {"status": ["PLACED"]}, portals=(O,)),
                      Action("ready", {"status": "READY"}, {"status": ["ACCEPTED"]}, portals=(O,)),
                      Action("picked-up", {"status": "PICKED_UP"}, {"status": ["READY"]}, portals=(O,)),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PLACED"]}, portals=(PA, O)))),
    Resource("partner-sale", "service_partners", "ptn.partner_sale",
             c("uid partner_id company_id user_id vehicle_id fuel_type qty unit_price amount points_used currency method status created_at"), (),
             {P: "partners.manage", O: None, PA: None}, create=False, update=False, group="station"),
    Resource("partner-settlement", "service_partners", "ptn.partner_settlement",
             c("partner_id period gross commission carrier_share redemptions net currency status"), (),
             {P: "partners.manage", O: None}, create=False, update=False, group="partners",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["DRAFT"]}, portals=(P,)),
                      Action("paid", {"status": "PAID"}, {"status": ["APPROVED"]}, portals=(P,)))),
    Resource("rest-stop-rating", "service_partners", "ptn.rest_stop_rating",
             c("partner_id user_id trip_id overall cleanliness service value comment created_at"),
             c("partner_id trip_id overall cleanliness service value comment"), {P: "partners.manage", O: None, PA: None},
             user_col="user_id", readonly_portals=(O,), group="station"),

    # ------------------------------------------------------------- loyalty partners
    Resource("loyalty-partner", "loyalty_partners", "pricing.loyalty_partner",
             c("program_id party_id partner_type earn_rate burn_rate conversion_ratio settlement_cycle status"),
             c("program_id party_id service_partner_id partner_type earn_rate burn_rate conversion_ratio settlement_cycle contract_ref"),
             {P: "loyalty.manage", PA: None}, readonly_portals=(PA,), group="loyalty",
             actions=(Action("activate", {"status": "ACTIVE"}, {"status": ["PENDING", "SUSPENDED"]}), suspend(),
                      Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("reward", "loyalty_partners", "pricing.reward_catalog",
             c("program_id loyalty_partner_id reward_type name points_cost conversion_value currency valid status"),
             c("program_id loyalty_partner_id reward_type name points_cost conversion_value currency commission_bp external_code valid"),
             {P: "loyalty.manage", PA: None}, readonly_portals=(PA,), group="loyalty", actions=(retire(),)),
    Resource("redemption-channel", "loyalty_partners", "pricing.redemption_channel", c("code min_points max_points active"),
             c("rules min_points max_points active"), {P: "loyalty.manage"}, create=False, order="code", group="loyalty"),
    Resource("award-seat-rule", "loyalty_partners", "pricing.award_seat_rule",
             c("company_id line_id route_id cabin points_cost quota valid status"),
             c("company_id line_id route_id cabin points_cost quota blackout_dates valid"), {P: "loyalty.manage", O: None},
             company_col="company_id", group="loyalty", actions=(retire(),)),
    Resource("voucher", "loyalty_partners", "pricing.reward_voucher",
             c("user_id catalog_id loyalty_partner_id points value currency expires_at used_at status"), (),
             {P: "loyalty.manage", PA: None}, create=False, update=False, group="loyalty",
             actions=(Action("cancel", {"status": "CANCELLED"}, {"status": ["ISSUED"]}, portals=(P,)),)),
    Resource("points-transfer", "loyalty_partners", "pricing.points_transfer",
             c("account_id loyalty_partner_id direction points external_units ratio status created_at"), (),
             {P: "loyalty.manage", PA: None}, create=False, update=False, group="loyalty"),
    Resource("points-liability", "loyalty_partners", "pricing.points_liability",
             c("program_id issuer_party_id period issued redeemed expired breakage_est"),
             c("program_id issuer_party_id period issued redeemed expired breakage_est"), {P: "loyalty.manage"}, group="loyalty"),
    Resource("partner-redemption", "loyalty_partners", "pricing.partner_redemption",
             c("loyalty_partner_id voucher_id points value commission currency redeemed_at"), (),
             {P: "loyalty.manage"}, create=False, update=False, order="redeemed_at DESC", group="loyalty"),

    # ------------------------------------------------------------- campaigns and sponsors (5.12)
    Resource("campaign", "campaigns", "pricing.campaign",
             c("code name company_id funding budget_total budget_spent per_user_limit priority valid status"),
             c("code name company_id audience_rule scope_rule trigger benefit funding budget_total per_user_limit per_day_limit "
               "stackable priority valid budget_alert_pct sponsor_account_id"), {P: "campaign.manage"}, creator_col="created_by",
             group="campaigns",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["DRAFT"]}, four_eyes=("created_by", "approved_by")),
                      Action("go-live", {"status": "LIVE"}, {"status": ["APPROVED", "PAUSED"]}),
                      Action("pause", {"status": "PAUSED"}, {"status": ["LIVE"]}),
                      Action("end", {"status": "ENDED"}, {"status": ["APPROVED", "LIVE", "PAUSED"]}))),
    Resource("promo-code", "campaigns", "pricing.promo_code", c("campaign_id code max_uses uses owner_party_id"),
             c("campaign_id code max_uses owner_party_id"), {P: "campaign.manage"}, group="campaigns"),
    Resource("sponsor", "campaigns", "pricing.sponsor_account", c("kind party_id wallet_id receivable_balance currency status"),
             c("kind party_id wallet_id currency"), {P: "campaign.manage"}, group="campaigns", actions=(suspend(), resume())),
    Resource("bin-range", "campaigns", "pricing.bin_range", c("bank_party_id from_bin to_bin card_type status"),
             c("bank_party_id from_bin to_bin card_type"), {P: "campaign.manage"}, group="campaigns", actions=(retire(),)),
    Resource("override-policy", "campaigns", "pricing.override_policy",
             c("target_type user_id company_id policy_key valid reason approved_by created_at"),
             c("target_type user_id company_id policy_key value valid reason"), {P: "payment.fee_policy"}, creator_col="created_by",
             group="campaigns", actions=(Action("approve", {}, {"approved_by": [None]}, four_eyes=("created_by", "approved_by")),)),

    # ------------------------------------------------------------- channels and intermediary platforms (14.7)
    Resource("channel", "intermediary_platforms", "sales.channel", c("code party_id channel_type relationship api_client_id status"),
             c("code party_id channel_type relationship api_client_id"), {P: "channels.manage", AG: None}, readonly_portals=(AG,),
             group="channels", actions=(suspend(), resume())),
    Resource("channel-agreement", "intermediary_platforms", "sales.channel_agreement",
             c("channel_id company_id model rate_bp commission_scheme_id settlement_cycle label valid status"),
             c("channel_id company_id model rate_bp commission_scheme_id scope fare_visibility markup_policy settlement_cycle label valid"),
             {P: "channels.manage", AG: None, O: None}, readonly_portals=(AG, O), creator_col="created_by", group="channels",
             actions=(Action("approve", {"status": "ACTIVE"}, {"status": ["DRAFT"]}, four_eyes=("created_by", "approved_by")),
                      suspend(), resume(), Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("inventory-rule", "intermediary_platforms", "sales.channel_inventory_rule",
             c("channel_id company_id route_id trip_type allotment_seats cutoff_min release_rule visibility"),
             c("channel_id company_id route_id trip_type allotment_seats cutoff_min release_rule visibility"),
             {P: "channels.manage", O: None, AG: None}, company_col="company_id", readonly_portals=(AG,), delete=True, group="channels"),
    Resource("channel-api-profile", "intermediary_platforms", "sales.channel_api_profile",
             c("channel_id api_client_id api_schema rate_limit_per_min look_to_book_limit cache_ttl_sec"),
             c("channel_id api_client_id api_schema rate_limit_per_min look_to_book_limit cache_ttl_sec ip_allow mtls_cert_ref"),
             {P: "channels.manage", AG: None}, readonly_portals=(AG,), order="channel_id", group="channels"),
    Resource("channel-statement", "intermediary_platforms", "sales.channel_statement",
             c("channel_id period gross_sales refunds commission taxes net_due currency status"), (),
             {P: "channels.manage", AG: None}, create=False, update=False, group="statements",
             actions=(Action("issue", {"status": "ISSUED"}, {"status": ["DRAFT"]}, portals=(P,)),
                      Action("dispute", {"status": "DISPUTED"}, {"status": ["ISSUED"]}, portals=(AG,)),
                      Action("settle", {"status": "SETTLED"}, {"status": ["ISSUED", "DISPUTED"]}, portals=(P,)))),
    Resource("channel-statement-line", "intermediary_platforms", "sales.channel_statement_line",
             c("statement_id line_no booking_id kind gross commission tax net"), (), {P: "channels.manage", AG: None},
             create=False, update=False, order="statement_id DESC, line_no", group="statements"),
    Resource("channel-memo", "intermediary_platforms", "sales.channel_memo",
             c("channel_id statement_id memo_type reason amount currency status created_at"),
             c("channel_id statement_id memo_type reason amount currency ref"), {P: "channels.manage", AG: None},
             readonly_portals=(AG,), group="statements",
             actions=(Action("accept", {"status": "ACCEPTED"}, {"status": ["ISSUED", "DISPUTED"]}, portals=(AG, P)),
                      Action("dispute", {"status": "DISPUTED"}, {"status": ["ISSUED"]}, portals=(AG,)),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["ISSUED", "DISPUTED"]}, portals=(P,)))),
    Resource("supplier-source", "intermediary_platforms", "sales.supplier_source", c("name source_type company_id protocol status"),
             c("name source_type company_id protocol credentials_ref"), {P: "channels.manage"}, group="content",
             actions=(Action("go-live", {"status": "ACTIVE"}, {"status": ["TESTING"]}), suspend(), resume())),
    Resource("external-mapping", "intermediary_platforms", "sales.external_mapping", c("source_id local_type local_id external_id"),
             c("source_id local_type local_id external_id"), {P: "channels.manage"}, delete=True,
             order="source_id, local_type, external_id", group="content"),

    # ------------------------------------------------------------- accounting operations (13.7)
    Resource("tax-code", "accounting_ops", "acct.tax_code", c("company_id code name rate account_id active"),
             c("code name rate account_id tax_rule_id active"), {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"},
             company_col="company_id", group="books"),
    Resource("cost-center", "accounting_ops", "acct.cost_center", c("company_id code name route_id station_id trip_id"),
             c("code name route_id station_id trip_id"), {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"},
             company_col="company_id", group="books"),
    Resource("sales-invoice", "accounting_ops", "acct.sales_invoice",
             c("invoice_no company_id customer_party_id issue_date due_date subtotal tax total currency status"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False, group="invoices",
             actions=(Action("cancel", {"status": "CANCELLED"}, {"status": ["DRAFT"]}),)),
    Resource("sales-invoice-line", "accounting_ops", "acct.sales_invoice_line",
             c("invoice_id line_no description qty unit_price tax_amount amount"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False,
             order="invoice_id DESC, line_no", group="invoices"),
    Resource("credit-note", "accounting_ops", "acct.credit_note", c("credit_no company_id invoice_id reason amount tax status created_at"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False, group="invoices"),
    Resource("cash-box", "accounting_ops", "acct.cash_box", c("company_id owner_party_id station_id currency account_id status"),
             c("owner_party_id station_id currency account_id"), {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"},
             company_col="company_id", group="cash", actions=(Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE"]}),)),
    Resource("cash-session", "accounting_ops", "acct.cash_session",
             c("cash_box_id opened_by opened_at opening_amount closed_at closing_amount expected_amount variance status"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False,
             order="opened_at DESC", group="cash"),
    Resource("cash-receipt", "accounting_ops", "acct.cash_receipt",
             c("receipt_no company_id method party_id invoice_id amount currency receipt_date"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False, group="cash"),
    Resource("cash-payment", "accounting_ops", "acct.cash_payment",
             c("voucher_no company_id method party_id amount currency purpose payment_date approved_by"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False, group="cash"),
    Resource("export-batch", "accounting_ops", "acct.export_batch", c("company_id format period checksum created_at"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False, group="books"),
    Resource("sync-job", "accounting_ops", "acct.sync_job", c("connection_id batch_ref started_at finished_at items_total items_failed status"), (),
             {P: "accounting.operate", O: "accounting.operate"}, create=False, update=False, order="started_at DESC", group="books"),
    Resource("sync-conflict", "accounting_ops", "acct.sync_conflict", c("item_id conflict_type resolution resolved_at"), (),
             {P: "accounting.operate", O: "accounting.operate"}, create=False, update=False, group="books",
             actions=(Action("keep-local", {"resolution": "KEEP_LOCAL"}, {"resolution": [None]}, stamp="resolved_at", by="resolved_by"),
                      Action("keep-external", {"resolution": "KEEP_EXTERNAL"}, {"resolution": [None]}, stamp="resolved_at", by="resolved_by"))),

    # ------------------------------------------------------------- contact center (7.11)
    Resource("call-queue", "contact_center", "crm.call_queue", c("code name channel sla_target_sec status"),
             c("code name channel sla_target_sec"), {P: "contact_center.manage"}, group="setup",
             actions=(Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE"]}), Action("open", {"status": "ACTIVE"}, {"status": ["CLOSED"]}))),
    Resource("call-skill", "contact_center", "crm.call_skill", c("code name"), c("code name"), {P: "contact_center.manage"},
             delete=True, order="code", group="setup"),
    Resource("call-agent", "contact_center", "crm.call_agent", c("user_id status"), c("user_id shift"), {P: "contact_center.manage"},
             group="setup", actions=(Action("available", {"status": "AVAILABLE"}, {}), Action("offline", {"status": "OFFLINE"}, {}))),
    Resource("agent-skill", "contact_center", "crm.call_agent_skill", c("agent_id skill_code level"), c("agent_id skill_code level"),
             {P: "contact_center.manage"}, delete=True, order="agent_id, skill_code", group="setup"),
    Resource("queue-skill", "contact_center", "crm.call_queue_skill", c("queue_id skill_code"), c("queue_id skill_code"),
             {P: "contact_center.manage"}, delete=True, order="queue_id, skill_code", group="setup"),
    Resource("call", "contact_center", "crm.call",
             c("uid direction queue_id party_id case_id agent_id handled_by state started_at ended_at outcome csat"), (),
             {P: "contact_center.manage"}, create=False, update=False, order="started_at DESC", filters=c("state outcome"), group="calls"),
    Resource("call-event", "contact_center", "crm.call_event", c("call_id ts kind"), (), {P: "contact_center.manage"},
             create=False, update=False, order="ts DESC", group="calls"),
    Resource("callback", "contact_center", "crm.callback_request", c("call_id reason due_at assigned_agent_id status"),
             c("assigned_agent_id due_at"), {P: "contact_center.manage"}, create=False, group="calls",
             actions=(Action("done", {"status": "DONE"}, {"status": ["PENDING"]}), Action("fail", {"status": "FAILED"}, {"status": ["PENDING"]}),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PENDING"]}))),
    Resource("call-qa", "contact_center", "crm.call_qa", c("call_id scorer scorer_user_id score flags created_at"),
             c("call_id score flags"), {P: "contact_center.manage"}, creator_col="scorer_user_id", defaults={"scorer": "HUMAN"},
             group="quality"),
    Resource("ai-eval-case", "contact_center", "crm.ai_eval_case", c("lang_dialect input expected last_result last_run_at active"),
             c("lang_dialect input expected active"), {P: "contact_center.manage"}, delete=True, group="quality"),

    # ------------------------------------------------------------- government adapters (phase 5)
    Resource("gov-adapter", "gov_adapters", "sec.gov_adapter_config", c("authority_id adapter_type endpoint protocol timeout_ms status"),
             c("authority_id adapter_type endpoint protocol cert_ref mapping timeout_ms"), {P: "gov_adapters.manage"}, group="adapters",
             actions=(Action("go-live", {"status": "ACTIVE"}, {"status": ["TESTING"]}), suspend(), resume(("SUSPENDED",)))),
    Resource("verification-job", "gov_adapters", "sec.verification_job",
             c("adapter_id subject_type subject_id request_ref status attempts requested_at completed_at"), (),
             {P: "gov_adapters.manage"}, create=False, update=False, order="requested_at DESC", filters=c("status subject_type"),
             group="adapters", actions=(Action("retry", {"status": "QUEUED"}, {"status": ["FAILED"]}),)),
]
