"""Launch completeness (readiness audit, October 2026): the tables of the launch phases that had no screen.

Complaints and claims, trip ratings, pricing setup, loyalty programmes, fleet records and trip templates, the security
console, finance controls, data governance, reference data, and the school transport phase. Rows written only by the
system (closed ledger days, reconciliation runs, security and tamper events) are read-only here.
"""
from ._base import Action, AG, D, P, O, PA, Resource, activate, c, resume, retire, suspend

FOUR = ("created_by", "approved_by")


def approve(when=("PENDING",), **kw) -> Action:
    """Activation by a second person: the approver must not be the author."""
    return Action("approve", {"status": "ACTIVE"}, {"status": list(when)}, four_eyes=FOUR, **kw)


RESOURCES = [
    # ------------------------------------------------------------- complaints, claims and service (7.6)
    Resource("case", "support_cases", "crm.case",
             c("ref kind category priority status channel subject party_id booking_id company_id assigned_to first_due_at "
               "resolve_due_at first_response_at sla_breached claim_amount approved_amount liable payout_status created_at"),
             c("kind category priority channel subject description party_id booking_id trip_id resolution claim_amount "
               "approved_amount liable"),
             {P: "case.handle", O: "case.handle"}, company_col="company_id", filters=("status", "kind", "priority", "payout_status"),
             group="cases",
             actions=(Action("take", {"status": "OPEN"}, {"status": ["NEW", "OPEN", "WAITING"]}, by="assigned_to"),
                      Action("wait", {"status": "WAITING"}, {"status": ["NEW", "OPEN"]}),
                      Action("resolve", {"status": "RESOLVED"}, {"status": ["NEW", "OPEN", "WAITING"]}),
                      Action("close", {"status": "CLOSED"}, {"status": ["RESOLVED"]}),
                      Action("reject", {"status": "REJECTED"}, {"status": ["NEW", "OPEN", "WAITING"]}),
                      Action("send_to_finance", {"payout_status": "PENDING_FINANCE"}, {"payout_status": ["NONE"]},
                             portals=(P,)))),
    Resource("case-event", "support_cases", "crm.case_event", c("case_id kind visibility actor_role actor_id body created_at"),
             c("case_id kind visibility body"), {P: "case.handle", O: "case.handle"}, creator_col="actor_id",
             defaults={"actor_role": "STAFF"}, update=False, order="id DESC", group="cases"),
    Resource("trip-rating", "support_cases", "crm.trip_rating",
             c("trip_id company_id stars punctuality comfort staff comment moderation created_at"), (),
             {P: "case.handle", O: None}, create=False, update=False, readonly_portals=(O,), filters=("moderation",),
             group="cases", actions=(Action("hide", {"moderation": "HIDDEN"}, {"moderation": ["VISIBLE"]}),
                                     Action("show", {"moderation": "VISIBLE"}, {"moderation": ["HIDDEN"]}))),
    Resource("refund-request", "support_cases", "sales.refund_request",
             c("booking_id ticket_id reason amount_requested amount_approved status requested_by decided_by created_at decided_at"), (),
             {P: "compensation.decide", O: None}, create=False, update=False, readonly_portals=(O, P), group="refunds"),
    Resource("passenger-compensation", "support_cases", "sales.passenger_compensation",
             c("booking_id trip_disruption_id type amount charged_to_company_id status created_at"), (),
             {P: "compensation.decide", O: None}, create=False, update=False, readonly_portals=(O, P), group="refunds"),
    Resource("waitlist-entry", "support_cases", "sales.waitlist_entry",
             c("trip_id party_id from_seq to_seq seats status offered_at offer_expires_at booking_id created_at"), (),
             {P: "case.handle", O: None}, create=False, update=False, readonly_portals=(O, P), group="refunds"),
    Resource("campaign-redemption", "support_cases", "sales.campaign_redemption",
             c("campaign_id promo_code_id booking_id party_id discount_amount sponsor_amount created_at"), (),
             {P: "campaign.manage"}, create=False, update=False, readonly_portals=(P,), group="refunds"),
    Resource("notification-template", "support_cases", "crm.notification_template", c("code channel locale subject active"),
             c("code channel locale subject body active"), {P: "case.handle"}, order="code, channel, locale", group="messages",
             actions=(Action("approve", {"active": True}, {"active": [False]}, by="approved_by"),
                      Action("deactivate", {"active": False}, {"active": [True]}))),

    # ------------------------------------------------------------- pricing setup (5.6 to 5.8)
    Resource("jurisdiction", "pricing_setup", "pricing.jurisdiction", c("country_code level parent_id name"),
             c("country_code level parent_id name"), {P: "pricing.tax_commission"}, order="country_code, name", group="tax"),
    Resource("tax-scheme", "pricing_setup", "pricing.tax_scheme",
             c("code name jurisdiction_id tax_type treatment collected_by valid version status created_by approved_by"),
             c("code name jurisdiction_id tax_type treatment scope collected_by payable_to_party_id valid"),
             {P: "pricing.tax_commission", O: None}, readonly_portals=(O,), creator_col="created_by", group="tax",
             actions=(approve(), retire())),
    Resource("tax-rule", "pricing_setup", "pricing.tax_rule",
             c("scheme_id seq calc_method rate amount base_type compound_mode min_amount max_amount applies_per priority"),
             c("scheme_id seq calc_method rate amount base_type base_include compound_mode min_amount max_amount rounding_rule "
               "applies_per priority"), {P: "pricing.tax_commission"}, order="scheme_id DESC, seq", group="tax"),
    Resource("commission-scheme", "pricing_setup", "pricing.commission_scheme",
             c("code type funded_by beneficiary_role base_type valid version status created_by approved_by"),
             c("code type funded_by beneficiary_role scope base_type valid"), {P: "pricing.tax_commission"},
             creator_col="created_by", group="commission", actions=(approve(), retire())),
    Resource("commission-rule", "pricing_setup", "pricing.commission_rule",
             c("scheme_id seq calc_method rate amount min_amount max_amount cap_period"),
             c("scheme_id seq calc_method rate amount min_amount max_amount cap_period"), {P: "pricing.tax_commission"},
             order="scheme_id DESC, seq", group="commission"),
    Resource("rate-band", "pricing_setup", "pricing.rate_band",
             c("tax_rule_id commission_rule_id dimension from_value to_value rate amount mode"),
             c("tax_rule_id commission_rule_id dimension from_value to_value rate amount mode"), {P: "pricing.tax_commission"},
             group="commission"),
    Resource("allocation-template", "pricing_setup", "pricing.allocation_template",
             c("code anchor_line_code rounding_line_code version status created_by approved_by created_at"),
             c("code scope anchor_line_code rounding_line_code"), {P: "pricing.tax_commission"}, creator_col="created_by",
             group="commission", actions=(approve(), retire())),
    Resource("allocation-template-line", "pricing_setup", "pricing.allocation_template_line",
             c("template_id code level parent_code component_type beneficiary_ref basis value wallet_type release_event refundable"),
             c("template_id code level parent_code component_type beneficiary_ref basis value rule_ref wallet_type release_event "
               "refundable"), {P: "pricing.tax_commission"}, delete=True, order="template_id DESC, level, code", group="commission"),
    Resource("cancellation-policy", "pricing_setup", "pricing.cancellation_policy",
             c("company_id code name version valid status approved_by"), c("code name rules valid"),
             {P: "pricing.tax_commission", O: "trip.publish"}, company_col="company_id", group="fares",
             actions=(Action("activate", {"status": "ACTIVE"}, {"status": ["DRAFT"]}, by="approved_by"), retire())),
    Resource("fare-table", "pricing_setup", "pricing.fare_table",
             c("scope company_id route_id currency locked min_price max_price valid version status created_by approved_by"),
             c("scope route_id currency locked min_price max_price valid"), {P: "pricing.tax_commission", O: "trip.publish"},
             company_col="company_id", creator_col="created_by", group="fares", actions=(approve(), retire())),
    Resource("fare-table-item", "pricing_setup", "pricing.fare_table_item",
             c("fare_table_id from_station_id to_station_id cabin passenger_category base_price"),
             c("fare_table_id from_station_id to_station_id cabin passenger_category base_price"),
             {P: "pricing.tax_commission", O: "trip.publish"}, delete=True, order="fare_table_id DESC, from_station_id, to_station_id",
             group="fares"),
    Resource("pricing-modifier", "pricing_setup", "pricing.pricing_modifier",
             c("company_id type action_type action_value priority valid active"),
             c("type condition action_type action_value priority valid active"),
             {P: "pricing.tax_commission", O: "trip.publish"}, company_col="company_id", group="fares"),

    # ------------------------------------------------------------- loyalty (5.12, 5.13)
    Resource("loyalty-program", "loyalty", "pricing.loyalty_program", c("code name point_value currency expiry_months status"),
             c("code name point_value currency expiry_months tax_treatment"), {P: "loyalty.manage"}, group="programme",
             actions=(Action("pause", {"status": "PAUSED"}, {"status": ["ACTIVE"]}), resume(("PAUSED",)),
                      Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE", "PAUSED"]}))),
    Resource("loyalty-tier", "loyalty", "pricing.loyalty_tier", c("program_id code name min_points"),
             c("program_id code name min_points benefits"), {P: "loyalty.manage"}, order="program_id DESC, min_points", group="programme"),
    Resource("loyalty-rule", "loyalty", "pricing.loyalty_rule", c("program_id kind funded_by valid version active"),
             c("program_id kind condition formula funded_by valid active"), {P: "loyalty.manage"}, group="programme"),
    Resource("points-account", "loyalty", "pricing.points_account", c("program_id party_id tier_id balance status created_at"), (),
             {P: "loyalty.manage", PA: None}, owner_col="party_id", create=False, update=False, readonly_portals=(PA,),
             group="members", actions=(Action("freeze", {"status": "FROZEN"}, {"status": ["ACTIVE"]}, portals=(P,)),
                                       Action("unfreeze", {"status": "ACTIVE"}, {"status": ["FROZEN"]}, portals=(P,)))),
    Resource("points-ledger", "loyalty", "pricing.points_ledger",
             c("account_id txn_type points booking_id rule_id funded_by expires_at created_at"), (),
             {P: "loyalty.manage", PA: None}, create=False, update=False, readonly_portals=(P, PA), group="members"),

    # ------------------------------------------------------------- fleet records and trip planning (4.13, 4.17, 7.x)
    Resource("trip-template", "fleet_records", "ops.trip_template",
             c("route_id service_number_id default_vehicle_id departure_time days_of_week base_price currency active status"),
             c("route_id service_number_id default_vehicle_id departure_time days_of_week fare_brand_codes base_price currency active"),
             {O: "trip.publish", P: None}, company_col="company_id", readonly_portals=(P,), filters=("status",), group="planning",
             actions=(Action("pause", {"status": "PAUSED"}, {"status": ["ACTIVE"]}), resume(("PAUSED",)),
                      retire(("ACTIVE", "PAUSED")))),
    Resource("service-number", "fleet_records", "net.service_number", c("company_id number block route_id direction valid created_at"),
             c("number block route_id direction valid"), {O: "trip.publish", P: None}, company_col="company_id",
             readonly_portals=(P,), group="planning"),
    Resource("trip-change", "fleet_records", "ops.trip_change",
             c("trip_id kind old_departure new_departure shift_min reason by_user_id created_at"), (),
             {O: None, P: None}, create=False, update=False, readonly_portals=(O, P), group="planning"),
    Resource("trip-disruption", "fleet_records", "ops.trip_disruption",
             c("trip_id incident_id decision replacement_vehicle_id partner_company_id decision_deadline decided_by decided_at status"),
             c("decision replacement_vehicle_id partner_company_id"), {O: "trip.reschedule", P: "trip.reschedule"}, create=False,
             group="planning", actions=(Action("decide", {"status": "DECIDED"}, {"status": ["AWAITING_DECISION"]},
                                               by="decided_by", stamp="decided_at"),
                                        Action("close", {"status": "CLOSED"}, {"status": ["DECIDED", "AUTO_FALLBACK"]}))),
    Resource("vehicle-swap", "fleet_records", "ops.vehicle_swap",
             c("trip_id from_vehicle_id to_vehicle_id reason seats_reassigned approved_by created_at"), (),
             {O: None, P: None}, create=False, update=False, readonly_portals=(O, P), group="planning"),
    Resource("insurance-policy", "fleet_records", "fleet.insurance_policy",
             c("vehicle_id insurer_name policy_no coverage_type passenger_cover cargo_cover period source verified_at status"),
             c("vehicle_id insurer_party_id insurer_name policy_no coverage_type passenger_cover cargo_cover limits period document_id"),
             {O: "vehicle.manage", P: "license.approve_change"}, group="vehicles",
             actions=(Action("verify", {"status": "VALID"}, {"status": ["PENDING"]}, portals=(P,), stamp="verified_at"),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PENDING", "VALID"]}))),
    Resource("vehicle-lease", "fleet_records", "fleet.vehicle_lease",
             c("vehicle_id owner_party_id lessee_company_id contract_no period status created_at"),
             c("vehicle_id owner_party_id contract_no period document_id"), {O: "vehicle.ownership", P: None},
             company_col="lessee_company_id", readonly_portals=(P,), group="vehicles",
             actions=(Action("terminate", {"status": "TERMINATED"}, {"status": ["ACTIVE"]}),)),
    Resource("vehicle-status-history", "fleet_records", "fleet.vehicle_status_history",
             c("vehicle_id status reason incident_id changed_by created_at"), (), {O: None, P: None}, create=False, update=False,
             readonly_portals=(O, P), group="vehicles"),
    Resource("license-change-request", "fleet_records", "fleet.license_change_request",
             c("license_record_id requested_by status reviewed_by approved_by decision_reason created_at decided_at"),
             c("license_record_id new_values document_id decision_reason"), {O: "vehicle.manage", P: "license.approve_change"},
             creator_col="requested_by", group="vehicles",
             actions=(Action("review", {"status": "REVIEWED"}, {"status": ["SUBMITTED"]}, portals=(P,),
                             four_eyes=("requested_by", "reviewed_by")),
                      Action("approve", {"status": "APPROVED"}, {"status": ["REVIEWED"]}, portals=(P,),
                             four_eyes=("reviewed_by", "approved_by"), stamp="decided_at"),
                      Action("reject", {"status": "REJECTED"}, {"status": ["SUBMITTED", "REVIEWED"]}, portals=(P,),
                             by="reviewed_by", stamp="decided_at"))),
    Resource("seat-price-rule", "fleet_records", "fleet.seat_price_rule",
             c("company_id vehicle_id seat_layout_id seat_nos price_delta label active"),
             c("vehicle_id seat_layout_id seat_nos price_delta label active"), {O: "vehicle.manage", P: None},
             company_col="company_id", readonly_portals=(P,), group="vehicles"),
    Resource("field-check-log", "fleet_records", "fleet.field_check_log",
             c("inspector_user_id vehicle_id method result lat lng created_at"), (), {P: "violation.review"}, create=False,
             update=False, readonly_portals=(P,), group="inspections"),
    Resource("inspection-check", "fleet_records", "sales.inspection_check",
             c("company_id inspector_party_id vehicle_id trip_id result fee_charged currency ts"), (),
             {O: None, P: "violation.review"}, create=False, update=False, readonly_portals=(O, P), group="inspections"),
    Resource("incident-evidence", "fleet_records", "ops.incident_evidence", c("incident_id file_id kind uploaded_by created_at"), (),
             {O: "incident.manage", P: "incident.manage"}, create=False, update=False, readonly_portals=(O, P), group="inspections"),
    Resource("station-contact", "fleet_records", "net.station_contact", c("station_id role name phone email"),
             c("station_id role name phone email"), {P: "station.approve", O: "stations.operate"}, delete=True, group="stations"),
    Resource("user-station-scope", "fleet_records", "iam.user_station_scope", c("user_id station_id company_id valid"),
             c("user_id station_id valid"), {O: "company.staff", P: None}, company_col="company_id", delete=True,
             readonly_portals=(P,), order="user_id DESC, station_id", group="stations"),

    # ------------------------------------------------------------- security console (16.x)
    Resource("blocklist-entry", "security_console", "sec.blocklist_entry", c("entry_type reason added_by created_at expires_at"),
             (), {P: "security.console"}, create=False, update=False, delete=True, order="created_at DESC",
             group="protection"),           # entries are added through /api/admin/support/blocklist, which hashes the value
    Resource("fraud-case", "security_console", "sec.fraud_case",
             c("subject_type rule_code status assigned_to outcome created_at closed_at subject_user_id subject_party_id subject_booking_id"),
             c("outcome"), {P: "security.console"}, create=False, filters=("status",), group="protection",
             actions=(Action("investigate", {"status": "INVESTIGATING"}, {"status": ["OPEN"]}, by="assigned_to"),
                      Action("confirm", {"status": "CONFIRMED"}, {"status": ["OPEN", "INVESTIGATING"]}, stamp="closed_at"),
                      Action("dismiss", {"status": "DISMISSED"}, {"status": ["OPEN", "INVESTIGATING"]}, stamp="closed_at"))),
    Resource("risk-assessment", "security_console", "sec.risk_assessment",
             c("subject_type event_type score decision created_at subject_user_id subject_party_id subject_booking_id subject_payment_id"), (),
             {P: "security.console"}, create=False, update=False, readonly_portals=(P,), group="protection"),
    Resource("sos-event", "security_console", "sec.sos_event", c("trip_id triggered_by lat lng status incident_id created_at"),
             c("incident_id"), {P: "incident.manage", O: "incident.manage"}, create=False, filters=("status",), group="alarms",
             actions=(Action("acknowledge", {"status": "ACKNOWLEDGED"}, {"status": ["OPEN"]}),
                      Action("close", {"status": "CLOSED"}, {"status": ["OPEN", "ACKNOWLEDGED"]}))),
    Resource("security-event", "security_console", "sec.security_event",
             c("source severity category user_id api_client_id ip correlation_id created_at"), (), {P: "audit.view"}, create=False,
             update=False, readonly_portals=(P,), filters=("severity", "category"), order="created_at DESC", group="logs"),
    Resource("tamper-event", "security_console", "sec.tamper_event",
             c("user_id api_client_id ip endpoint field client_value server_value created_at"), (), {P: "audit.view"},
             create=False, update=False, readonly_portals=(P,), order="created_at DESC", group="logs"),
    Resource("break-glass-log", "security_console", "sec.break_glass_log",
             c("actor_id reason approver_id started_at ended_at expires_at incident_ref emergency reviewed_at review_note"),
             c("review_note"), {P: "audit.view"}, create=False, order="started_at DESC", group="logs",
             actions=(Action("mark_reviewed", {}, {"reviewed_at": [None]}, stamp="reviewed_at"),)),
    Resource("access-review", "security_console", "sec.access_review", c("user_id role_id reviewer_id decision reviewed_on due_on scope"),
             c("user_id role_id decision reviewed_on due_on scope"), {P: "security.console"}, creator_col="reviewer_id",
             group="access"),
    Resource("beneficial-owner", "security_console", "iam.beneficial_owner", c("company_id party_id ownership_pct"),
             c("company_id party_id ownership_pct"), {P: "company.approve"}, delete=True, order="company_id DESC", group="access"),
    Resource("verification", "security_console", "iam.verification",
             c("subject_type level method doc_type doc_expiry liveness_score match_score decision reason_code reviewer_id"), (),
             {P: "company.approve"}, create=False, update=False, readonly_portals=(P,), group="access"),
    Resource("authority-data-request", "security_console", "sec.authority_data_request",
             c("authority_id official_ref legal_basis requested_by approved_by status delivered_at delivery_ref created_at"),
             c("authority_id official_ref legal_basis scope delivery_ref"), {P: "authority.requests"}, creator_col="requested_by",
             group="authorities",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["PENDING"]}, four_eyes=("requested_by", "approved_by")),
                      Action("deliver", {"status": "DELIVERED"}, {"status": ["APPROVED"]}, stamp="delivered_at"),
                      Action("reject", {"status": "REJECTED"}, {"status": ["PENDING"]}))),
    Resource("authority-order", "security_console", "sec.authority_order",
             c("authority_id order_ref order_type target_type status received_at executed_at executed_by"), (),
             {P: "authority.requests"}, create=False, update=False, readonly_portals=(P,), group="authorities"),
    Resource("document-signature", "security_console", "sec.document_signature",
             c("doc_type doc_ref_id serial_no key_id issued_at revoked_at"), (), {P: "audit.view"}, create=False, update=False,
             readonly_portals=(P,), order="issued_at DESC", group="logs"),

    # ------------------------------------------------------------- finance controls (6.x, 13)
    Resource("gl-account", "finance_controls", "acct.gl_account",
             c("company_id code name account_type parent_id currency is_postable external_code active"),
             c("code name account_type parent_id currency is_postable external_code active"),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, company_col="company_id",
             order="code", group="ledger"),
    Resource("gl-period", "finance_controls", "acct.gl_period", c("company_id period status closed_by closed_at"), c("period"),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, company_col="company_id",
             order="period DESC", group="ledger",
             actions=(Action("close", {"status": "CLOSED"}, {"status": ["OPEN"]}, by="closed_by", stamp="closed_at"),)),
    Resource("journal-entry", "finance_controls", "acct.journal_entry",
             c("entry_no entry_date source_type posting_rule_id currency memo status posted_at"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False,
             readonly_portals=(P, O, AG), order="entry_date DESC, id DESC", group="ledger"),
    Resource("journal-line", "finance_controls", "acct.journal_line", c("entry_id account_id party_id cost_center_id debit credit memo"), (),
             {P: "accounting.operate", O: "accounting.operate", AG: "accounting.operate"}, create=False, update=False,
             readonly_portals=(P, O, AG), group="ledger"),
    Resource("posting-rule", "finance_controls", "acct.posting_rule", c("event_type version active created_by approved_by"),
             c("event_type condition lines_template active"), {P: "accounting.operate"}, creator_col="created_by", group="ledger",
             actions=(Action("approve", {"active": True}, {"active": [False]}, four_eyes=FOUR),
                      Action("deactivate", {"active": False}, {"active": [True]}))),
    Resource("tax-registration", "finance_controls", "acct.tax_registration", c("profile_id tax_scheme_id filing_frequency registered"),
             c("profile_id tax_scheme_id filing_frequency registered"), {P: "einvoice.manage"}, group="tax"),
    Resource("tax-return", "finance_controls", "acct.tax_return",
             c("profile_id authority_id tax_scheme_id period status submitted_at authority_ref created_at"),
             c("profile_id authority_id tax_scheme_id period authority_ref"), {P: "einvoice.manage"}, group="tax",
             actions=(Action("reconcile", {"status": "RECONCILED"}, {"status": ["DRAFT"]}),
                      Action("submit", {"status": "SUBMITTED"}, {"status": ["RECONCILED"]}, stamp="submitted_at"),
                      Action("mark_paid", {"status": "PAID"}, {"status": ["SUBMITTED"]}))),
    Resource("tax-return-line", "finance_controls", "acct.tax_return_line", c("return_id box_code amount source_note"),
             c("return_id box_code amount source_note"), {P: "einvoice.manage"}, order="return_id DESC, box_code", group="tax"),
    Resource("tax-payment", "finance_controls", "acct.tax_payment",
             c("profile_id authority_id tax_return_id tax_scheme_id amount currency paid_at ref ledger_txn_id"), (),
             {P: "einvoice.manage"}, create=False, update=False, readonly_portals=(P,), group="tax"),
    Resource("tax-ledger", "finance_controls", "fin.tax_ledger",
             c("jurisdiction_id tax_scheme_id company_id period direction currency base tax created_at"), (),
             {P: "einvoice.manage"}, create=False, update=False, readonly_portals=(P,), order="created_at DESC", group="tax"),
    Resource("einvoice-document", "finance_controls", "acct.einvoice_document",
             c("uuid doc_type subtype company_id buyer_tax_no currency subtotal tax_total total number status"), (),
             {P: "einvoice.manage", O: "einvoice.manage"}, create=False, update=False, readonly_portals=(P, O), group="tax"),
    Resource("einvoice-submission", "finance_controls", "acct.einvoice_submission",
             c("document_id attempt mode sent_at response_status authority_ref"), (), {P: "einvoice.manage"}, create=False,
             update=False, readonly_portals=(P,), group="tax"),
    Resource("bank-reconciliation", "finance_controls", "fin.bank_reconciliation",
             c("recon_date account_label currency bank_balance wallets_total receivables diff status reviewed_by created_at"),
             c("recon_date account_label currency bank_balance wallets_total receivables"), {P: "ledger.reconcile"},
             order="recon_date DESC", group="treasury",
             actions=(Action("matched", {"status": "MATCHED"}, {"status": ["OPEN", "INVESTIGATING"]}, by="reviewed_by"),
                      Action("investigate", {"status": "INVESTIGATING"}, {"status": ["OPEN"]}, by="reviewed_by"))),
    Resource("cash-remittance", "finance_controls", "fin.cash_remittance",
             c("company_id amount currency method ref ledger_txn_id recorded_by reconciled_at created_at"), (),
             {P: "cash.remittance"}, create=False, update=False, readonly_portals=(P,), group="treasury"),
    Resource("float-account", "finance_controls", "fin.float_account", c("bank_party_id kind currency account_ref ledger_wallet_id status"),
             c("bank_party_id kind currency account_ref ledger_wallet_id"), {P: "ledger.reconcile"}, group="treasury",
             actions=(Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE"]}),)),
    Resource("deposit-placement", "finance_controls", "fin.deposit_placement",
             c("account_id product principal rate_bp starts_on matures_on status"),
             c("account_id product principal rate_bp starts_on matures_on"), {P: "ledger.reconcile"}, group="treasury",
             actions=(Action("matured", {"status": "MATURED"}, {"status": ["ACTIVE"]}),
                      Action("break", {"status": "BROKEN"}, {"status": ["ACTIVE"]}))),
    Resource("float-report", "finance_controls", "fin.float_report",
             c("report_date currency liabilities assets coverage_ratio liquid_ratio yield_accrued created_at"), (),
             {P: "ledger.reconcile"}, create=False, update=False, readonly_portals=(P,), order="report_date DESC", group="treasury"),
    Resource("payout", "finance_controls", "fin.payout",
             c("company_id settlement_batch_id period currency gross holdback net status bank_ref"), (),
             {P: "payout.run", O: "company.payout_schedule"}, create=False, update=False, readonly_portals=(P, O), group="payouts"),
    Resource("payout-schedule", "finance_controls", "fin.payout_schedule",
             c("company_id frequency weekday month_day holdback_pct min_amount status updated_at"), (),
             {P: "payout.run", O: "company.payout_schedule"}, create=False, update=False, readonly_portals=(P, O),
             order="company_id", group="payouts"),
    Resource("wallet-reconciliation", "finance_controls", "fin.wallet_reconciliation", c("run_at wallets mismatches"), (),
             {P: "ledger.reconcile"}, create=False, update=False, readonly_portals=(P,), order="run_at DESC", group="controls"),
    Resource("ledger-close", "finance_controls", "fin.ledger_close", c("closed_through closed_at"), (), {P: "ledger.reconcile"},
             create=False, update=False, readonly_portals=(P,), order="closed_through DESC", group="controls"),
    Resource("ledger-day-total", "finance_controls", "fin.ledger_day_total", c("wallet_id day credit debit entries running_total"), (),
             {P: "ledger.reconcile"}, create=False, update=False, readonly_portals=(P,), order="day DESC, wallet_id", group="controls"),
    Resource("posting-batch", "finance_controls", "fin.posting_batch",
             c("uid source currency control_total entry_count closed_at created_by created_at"), (), {P: "ledger.reconcile"},
             create=False, update=False, readonly_portals=(P,), group="controls"),
    Resource("billed-usage", "finance_controls", "bill.billed_usage", c("company_id subscription_id invoice_id kind qty period_start"), (),
             {P: "billing.manage", O: "company.billing"}, create=False, update=False, readonly_portals=(P, O), group="payouts"),

    # ------------------------------------------------------------- data governance (16.13, 16.24)
    Resource("retention-policy", "data_governance", "gov.retention_policy",
             c("code dataset retention_days action legal_basis created_at"), (), {P: "privacy.manage"}, create=False,
             update=False, readonly_portals=(P,), order="dataset", group="privacy"),   # changed by schema files only (1047)
    Resource("data-inventory", "data_governance", "gov.data_inventory",
             c("dataset data_class owner purpose legal_basis retention_days location erasure_method backup_retention_days"), (),
             {P: "privacy.manage"}, create=False, update=False, readonly_portals=(P,), order="dataset", group="privacy"),
    Resource("data-purpose", "data_governance", "gov.data_purpose", c("code description requires_reason requires_second_approval"),
             (), {P: "privacy.manage"}, create=False, update=False, readonly_portals=(P,), order="code", group="privacy"),
    Resource("legal-hold", "data_governance", "gov.legal_hold",
             c("uid scope_type scope_id dataset reason case_ref placed_by placed_at released_by released_at"),
             c("scope_type scope_id dataset reason case_ref"), {P: "privacy.manage"}, creator_col="placed_by", group="privacy",
             actions=(Action("release", {}, {"released_at": [None]}, by="released_by", stamp="released_at"),)),
    Resource("privacy-incident", "data_governance", "gov.privacy_incident",
             c("detected_at data_class affected_count status notified_authority_at notified_subjects_at security_event_id"),
             c("detected_at data_class affected_count description security_event_id"), {P: "privacy.manage"}, group="incidents",
             actions=(Action("contain", {"status": "CONTAINED"}, {"status": ["OPEN"]}),
                      Action("authority_notified", {}, {"notified_authority_at": [None]}, stamp="notified_authority_at"),
                      Action("subjects_notified", {}, {"notified_subjects_at": [None]}, stamp="notified_subjects_at"),
                      Action("close", {"status": "CLOSED"}, {"status": ["OPEN", "CONTAINED"]}))),
    Resource("obligation", "data_governance", "gov.obligation_register",
             c("source ref_no title effective_date control_ref owner_user_id status next_review"),
             c("source ref_no title effective_date control_ref evidence_file_id owner_user_id status next_review"),
             {P: "obligation.manage"}, filters=("status",), group="compliance"),
    Resource("partner-dpa", "data_governance", "gov.partner_dpa",
             c("partner_party_id purpose retention_days processing_location signed_at review_at"),
             c("partner_party_id purpose data_fields retention_days processing_location signed_at review_at file_id"),
             {P: "privacy.manage"}, group="compliance"),
    Resource("feature-compliance-review", "data_governance", "gov.feature_compliance_review",
             c("feature decision approved_by created_at"), (), {P: "obligation.manage"}, create=False, update=False,
             readonly_portals=(P,), group="compliance"),

    # ------------------------------------------------------------- reference data
    Resource("currency", "reference_data", "ref.currency", c("code name minor_unit is_active"), c("code name minor_unit is_active"),
             {P: "reference.manage"}, order="code", group="money"),
    Resource("exchange-rate", "reference_data", "ref.exchange_rate", c("base_currency quote_currency rate source valid_from created_at"),
             c("base_currency quote_currency rate source valid_from"), {P: "reference.manage"}, order="valid_from DESC", group="money"),
    Resource("trip-type", "reference_data", "ref.trip_type", c("code name module is_system is_active sort"),
             c("code name module is_active sort"), {P: "reference.manage"}, order="sort, code", group="catalogues"),
    Resource("vehicle-class", "reference_data", "ref.vehicle_class", c("code name module is_system is_active sort"),
             c("code name module is_active sort"), {P: "reference.manage"}, order="sort, code", group="catalogues"),
    Resource("cargo-category", "reference_data", "ref.cargo_category",
             c("code name module is_system is_active sort dangerous needs_temperature"),
             c("code name module is_active sort dangerous needs_temperature"), {P: "reference.manage"}, order="sort, code",
             group="catalogues"),
    Resource("station-subtype", "reference_data", "ref.station_subtype", c("code name module is_system is_active sort"),
             c("code name module is_active sort"), {P: "reference.manage"}, order="sort, code", group="catalogues"),
    Resource("party-role-type", "reference_data", "ref.party_role_type", c("code name module is_system is_active sort"), (),
             {P: "reference.manage"}, create=False, update=False, readonly_portals=(P,), order="sort, code", group="catalogues"),
    Resource("translation", "reference_data", "ref.translation", c("entity entity_key field locale value updated_at"),
             c("entity entity_key field locale value"), {P: "reference.manage"}, order="entity, entity_key, field, locale",
             group="catalogues"),
    Resource("compliance-profile", "reference_data", "net.compliance_profile",
             c("subject country_code station_class version status created_by approved_by created_at"),
             c("subject country_code station_class spec"), {P: "station.approve"}, creator_col="created_by", group="catalogues",
             actions=(approve(), retire())),
    Resource("city-rollout", "reference_data", "sys.city_rollout", c("feature_key city_id stage status opens_on note updated_at"),
             (), {P: "modules.manage"}, create=False, update=False, readonly_portals=(P,), order="feature_key, city_id",
             group="rollout"),         # opened city by city through the module switches (1042)

    # ------------------------------------------------------------- school transport (21.3)
    Resource("school", "school_transport", "sch.school",
             c("company_id ministry_code sector education_license_no city_id station_id status created_at"),
             c("ministry_code sector education_license_no city_id station_id lat lng"), {P: "school.manage", O: "school.operate"},
             company_col="company_id", group="schools",
             actions=(activate(("PENDING", "SUSPENDED"), portals=(P,)), suspend(portals=(P,)))),
    Resource("school-operator", "school_transport", "sch.operator",
             c("company_id operator_kind school_id school_transport_license_no license_issuer license_expiry status approved_by approved_at"),
             c("operator_kind school_id government_contract_no supervising_authority school_transport_license_no license_issuer "
               "license_expiry license_record_id"), {P: "school.manage", O: "school.operate"}, company_col="company_id",
             group="schools",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["PENDING", "SUSPENDED"]}, portals=(P,),
                             by="approved_by", stamp="approved_at"),
                      Action("suspend", {"status": "SUSPENDED"}, {"status": ["APPROVED"]}, portals=(P,)),
                      Action("revoke", {"status": "REVOKED"}, {"status": ["PENDING", "APPROVED", "SUSPENDED"]}, portals=(P,)))),
    Resource("school-contract", "school_transport", "sch.contract",
             c("operator_id contract_kind school_id guardian_party_id school_year valid pricing_mode price currency status signed_at"),
             c("operator_id contract_kind school_id guardian_party_id school_year valid pricing_mode price currency "
               "school_transport_license_no license_authority terms"),
             {P: None, O: "school.operate", PA: None}, company_col="company_id", readonly_portals=(P, PA), group="contracts",
             actions=(Action("activate", {"status": "ACTIVE"}, {"status": ["DRAFT", "SUSPENDED"]}, stamp="signed_at"),
                      suspend(), Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("school-route", "school_transport", "sch.route",
             c("operator_id school_id code direction vehicle_id driver_party_id attendant_party_id depart_time max_ride_min status"),
             c("operator_id school_id code direction vehicle_id driver_party_id attendant_party_id path corridor_m max_ride_min "
               "depart_time operating_days"), {P: None, O: "school.operate"}, company_col="company_id", readonly_portals=(P,),
             group="routes", actions=(activate(("DRAFT", "SUSPENDED")), suspend(), retire(("ACTIVE", "SUSPENDED")))),
    Resource("school-route-stop", "school_transport", "sch.route_stop", c("route_id seq label station_id lat lng planned_offset_min"),
             c("route_id seq label station_id lat lng planned_offset_min"), {P: None, O: "school.operate"}, delete=True,
             readonly_portals=(P,), order="route_id DESC, seq", group="routes"),
    Resource("student", "school_transport", "sch.student",
             c("school_id party_id family_member_id student_no grade class_name status created_at"),
             c("school_id party_id family_member_id student_no grade class_name"), {P: None, O: "school.operate", PA: None},
             readonly_portals=(P, PA), group="pupils", actions=(Action("left", {"status": "LEFT"}, {"status": ["ACTIVE"]}),)),
    Resource("student-guardian", "school_transport", "sch.student_guardian",
             c("student_id party_id role relation is_primary can_receive receive_blocked verified_at"),
             c("student_id party_id role relation is_primary can_receive receive_blocked"), {P: None, O: "school.operate", PA: None},
             readonly_portals=(P, PA), order="student_id DESC", group="pupils",
             actions=(Action("verify", {}, {"verified_at": [None]}, by="verified_by", stamp="verified_at", portals=(O,)),
                      Action("block_receiving", {"receive_blocked": True}, {"receive_blocked": [False]}, portals=(O,)),
                      Action("allow_receiving", {"receive_blocked": False}, {"receive_blocked": [True]}, portals=(O,)))),
    Resource("enrollment", "school_transport", "sch.enrollment",
             c("contract_id student_id to_route_id to_stop_seq from_route_id from_stop_seq guardian_consent consent_at status created_at"),
             c("contract_id student_id to_route_id to_stop_seq from_route_id from_stop_seq"),
             {P: None, O: "school.operate", PA: None}, readonly_portals=(P,), group="pupils",
             actions=(Action("give_consent", {"guardian_consent": "GIVEN"}, {"guardian_consent": ["PENDING", "REFUSED"]}, portals=(PA,)),
                      Action("refuse_consent", {"guardian_consent": "REFUSED"}, {"guardian_consent": ["PENDING", "GIVEN"]},
                             portals=(PA,)),
                      Action("activate", {"status": "ACTIVE"}, {"status": ["PENDING", "PAUSED"]}, portals=(O,)),
                      Action("pause", {"status": "PAUSED"}, {"status": ["ACTIVE"]}, portals=(O,)),
                      Action("end", {"status": "ENDED"}, {"status": ["PENDING", "ACTIVE", "PAUSED"]}, portals=(O,)))),
    Resource("school-run", "school_transport", "sch.run",
             c("route_id run_date status started_at completed_at sweep_checked_at sweep_checked_by"), c("route_id run_date"),
             {P: None, O: "school.operate", PA: None}, readonly_portals=(P, PA), order="run_date DESC, id DESC", group="runs",
             actions=(Action("start", {"status": "IN_PROGRESS"}, {"status": ["PLANNED"]}),
                      Action("bus_checked_empty", {}, {"sweep_checked_at": [None]}, stamp="sweep_checked_at"),
                      Action("complete", {"status": "COMPLETED"}, {"status": ["IN_PROGRESS"]}),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PLANNED"]}))),
    Resource("school-attendance", "school_transport", "sch.attendance",
             c("run_id enrollment_id event received_by_party_id occurred_at source recorded_by"),
             c("run_id enrollment_id event received_by_party_id source lat lng"), {P: None, O: "school.operate", PA: None, D: None},
             creator_col="recorded_by", update=False, readonly_portals=(P, PA), order="occurred_at DESC, id DESC", group="runs"),
    Resource("absence-notice", "school_transport", "sch.absence_notice",
             c("enrollment_id absent_on direction reported_by_party_id reported_at"), c("enrollment_id absent_on direction"),
             {P: None, O: "school.operate", PA: None}, owner_col="reported_by_party_id", update=False, readonly_portals=(P,),
             order="absent_on DESC", group="runs"),

    # ------------------------------------------------------------- tables of later phases without a screen until now
    Resource("line-permit-vehicle", "approved_lines", "fleet.line_permit_vehicle",
             c("permit_id company_id vehicle_id valid status approved_by created_at"), c("permit_id vehicle_id valid"),
             {P: "lines.manage", O: "lines.operate"}, company_col="company_id", group="permits",
             actions=(Action("approve", {"status": "ACTIVE"}, {"status": ["SUSPENDED"]}, portals=(P,), by="approved_by"),
                      suspend(portals=(P,)), Action("remove", {"status": "REMOVED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("line-diversion", "approved_lines", "net.line_diversion",
             c("line_id active corridor_m reason issued_by reference_no approved_by status created_at"),
             (), {P: "lines.manage", O: None}, create=False, update=False, readonly_portals=(P, O), group="lines"),
    Resource("vehicle-qr-tag", "approved_lines", "fleet.vehicle_qr_tag", c("vehicle_id issued_at revoked_at"), (),
             {P: "lines.manage", O: None}, create=False, readonly_portals=(O,), group="permits",
             actions=(Action("revoke", {}, {"revoked_at": [None]}, stamp="revoked_at"),)),
    Resource("tracking-device", "tracking_stations", "fleet.tracking_device",
             c("company_id vehicle_id provider serial_no protocol certificate_no installed status created_at"),
             c("vehicle_id provider serial_no protocol certificate_no installed"), {P: "tracking.all", O: "tracking.own"},
             company_col="company_id", group="devices",
             actions=(activate(("PENDING", "FAULTY")), Action("faulty", {"status": "FAULTY"}, {"status": ["ACTIVE"]}),
                      Action("remove", {"status": "REMOVED"}, {"status": ["PENDING", "ACTIVE", "FAULTY"]}))),
    Resource("custody-transfer", "cargo", "ship.custody_transfer", c("shipment_id unit_id from_party_id to_party_id method ts"), (),
             {P: None, O: None}, create=False, update=False, readonly_portals=(P, O), order="ts DESC", group="shipments"),
    Resource("shipment-party", "cargo", "ship.shipment_party", c("shipment_id role party_id name id_type address_id"), (),
             {P: None, O: None}, create=False, update=False, readonly_portals=(P, O), order="shipment_id DESC, role",
             group="shipments"),
    Resource("shipment-option", "cargo", "ship.shipment_option", c("shipment_id option_id"), (), {P: None, O: None}, create=False,
             update=False, readonly_portals=(P, O), order="shipment_id DESC", group="shipments"),
    Resource("screening-request", "international", "sec.screening_request",
             c("authority_id subject_type context_type status requested_at subject_passenger_id context_trip_id context_booking_id"), (),
             {P: "watchlist.manage"}, create=False, update=False, readonly_portals=(P,), group="screening"),
    Resource("screening-result", "international", "sec.screening_result",
             c("request_id decision reason_code silent_flag response_ref valid_until reviewed_by created_at"), (),
             {P: "watchlist.manage"}, create=False, update=False, readonly_portals=(P,), order="request_id DESC", group="screening"),
    Resource("watchlist-entry", "international", "sec.watchlist_entry",
             c("authority_id identifier_type action valid source_ref status created_by"),
             (), {P: "watchlist.manage"}, create=False, update=False, group="screening",   # entries arrive from authorities
             actions=(Action("lift", {"status": "LIFTED"}, {"status": ["ACTIVE"]}),)),
    Resource("violation-report", "gov_adapters", "ops.violation_report",
             c("violation_id authority channel status external_ref sent_at created_at"), (), {P: "violation.review"},
             create=False, update=False, readonly_portals=(P,), group="reports"),
    Resource("incident-external-link", "gov_adapters", "ops.incident_external_link",
             c("incident_id authority external_ref status last_sync_at"), (), {P: "incident.manage"}, create=False, update=False,
             readonly_portals=(P,), group="reports"),
    Resource("partner-order-item", "service_partners", "ptn.partner_order_item", c("order_id menu_item_id qty unit_price"), (),
             {P: "partners.manage", O: None, PA: None}, create=False, update=False, readonly_portals=(P, O, PA),
             order="order_id DESC", group="orders"),
    Resource("channel-booking-ref", "intermediary_platforms", "sales.channel_booking_ref",
             c("booking_id channel_id external_locator agent_ref sub_agent_ref"), (), {P: "channels.manage", AG: None},
             create=False, update=False, readonly_portals=(P, AG), order="booking_id DESC", group="channels"),
    Resource("rental-booking-addon", "car_rental", "rent.rental_booking_addon", c("booking_id addon_id qty amount"), (),
             {P: None, O: None, PA: None}, create=False, update=False, readonly_portals=(P, O, PA), order="booking_id DESC",
             group="bookings"),
]
