"""Approved lines and tariffs (4.15), shuttle rides and subscriptions (7.13, phase 2)."""
from ._base import Action, P, O, PA, D, Resource, activate, c, retire, suspend

M_LINES, M_RIDES, M_SUBS = "approved_lines", "shuttle_rides", "shuttle_subscriptions"
PLAT = {P: "lines.manage", O: None}

RESOURCES = [
    Resource("line", M_LINES, "net.line", c("code name kind fare_regime city_id status"),
             c("code name kind fare_regime city_id"), PLAT, readonly_portals=(O,), group="catalog",
             actions=(activate(("DRAFT", "SUSPENDED")), suspend(), retire(("ACTIVE", "SUSPENDED")))),
    Resource("line-version", M_LINES, "net.line_version",
             c("line_id version distance_km typical_min corridor_m effective_from status"),
             c("line_id version geometry distance_km typical_min corridor_m effective_from"), PLAT,
             readonly_portals=(O,), group="catalog",
             actions=(Action("submit", {"status": "PENDING_APPROVAL"}, {"status": ["DRAFT"]}),
                      Action("publish", {"status": "ACTIVE"}, {"status": ["APPROVED"]}),
                      retire(("ACTIVE", "APPROVED")))),
    Resource("line-stop", M_LINES, "net.line_stop",
             c("line_version_id seq station_id mandatory geofence_m arr_offset_min dep_offset_min"),
             c("line_version_id seq station_id mandatory geofence_m arr_offset_min dep_offset_min"), PLAT,
             readonly_portals=(O,), delete=True, order="line_version_id, seq", group="catalog"),
    Resource("line-version-approval", M_LINES, "net.line_version_approval", c("line_version_id user_id role approved_at"),
             (), {P: "lines.manage"}, create=False, update=False, order="approved_at DESC", group="catalog"),
    Resource("line-permit", M_LINES, "net.line_permit",
             c("line_id company_id permit_no valid max_vehicles max_trips_day status"),
             c("line_id company_id permit_no valid max_vehicles max_trips_day"), PLAT, readonly_portals=(O,),
             group="permits", actions=(activate(("PENDING", "SUSPENDED")), suspend(),
                                       Action("revoke", {"status": "REVOKED"}, {"status": ["PENDING", "ACTIVE", "SUSPENDED"]}))),
    Resource("line-tariff", M_LINES, "net.line_tariff",
             c("line_id version regime mode currency valid_from status approved_at"),
             c("line_id version regime mode currency valid_from"), PLAT, readonly_portals=(O,), group="tariffs",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["DRAFT"]}, stamp="approved_at", by="approved_by"),
                      Action("publish", {"status": "ACTIVE"}, {"status": ["APPROVED"]}),
                      retire(("ACTIVE", "APPROVED")))),
    Resource("line-fare", M_LINES, "net.line_fare",
             c("tariff_id from_station_id to_station_id passenger_category fare band_to_seq per_km"),
             c("tariff_id from_station_id to_station_id passenger_category fare band_to_seq per_km"), PLAT,
             readonly_portals=(O,), delete=True, group="tariffs"),
    Resource("timetable", M_LINES, "net.timetable_template",
             c("line_id company_id kind days times headway_min window_from window_to valid status"),
             c("line_id company_id kind days times headway_min window_from window_to valid"),
             {P: "lines.manage", O: "lines.operate"}, company_col="company_id", group="operation",
             actions=(activate(("DRAFT",)), retire())),
    Resource("route-adherence", M_LINES, "ops.route_adherence_event", c("trip_id kind ts lat lng"), (),
             {P: "lines.manage", O: None}, create=False, update=False, order="ts DESC", group="operation"),

    # ------------------------------------------------------------- shuttle rides
    Resource("presence-beacon", M_RIDES, "ops.presence_beacon", c("trip_id vehicle_id source key_id rotation_sec active"),
             c("trip_id vehicle_id source key_id rotation_sec active"), {P: None, O: "lines.operate", D: None},
             readonly_portals=(P,), group="rides"),
    Resource("shuttle-ride", M_RIDES, "ops.shuttle_ride",
             c("uid user_id trip_id line_id board_station_id board_ts alight_station_id alight_ts alight_method "
               "charged_amount outstanding_amount currency status"), (),
             {P: None, O: None, PA: None, D: None}, create=False, update=False, order="board_ts DESC", group="rides",
             actions=(Action("dispute", {"status": "DISPUTED"}, {"status": ["CLOSED", "REVIEW"]}, portals=(PA,)),
                      Action("close-review", {"status": "CLOSED"}, {"status": ["REVIEW", "DISPUTED"]}, portals=(P,)))),
    Resource("ride-charge", M_RIDES, "ops.ride_segment_charge", c("ride_id seq_from seq_to amount kind ts"), (),
             {P: None, O: None, PA: None}, create=False, update=False, order="ts", group="rides"),

    # ------------------------------------------------------------- subscriptions and passes
    Resource("shuttle-zone", M_SUBS, "sales.shuttle_zone", c("code name city_id status"), c("code name city_id polygon"),
             {P: "shuttle.manage", O: None}, readonly_portals=(O,), group="passes", actions=(retire(),)),
    Resource("subscription-plan", M_SUBS, "sales.subscription_plan",
             c("code name company_id line_id zone_id period_days rides_limit passenger_category price currency status"),
             c("code name company_id line_id zone_id period_days rides_limit passenger_category price currency"),
             {P: "shuttle.manage", O: "lines.operate", PA: None}, company_col="company_id", readonly_portals=(PA,),
             group="passes", actions=(activate(("DRAFT",)), retire())),
    Resource("subscription", M_SUBS, "sales.subscription",
             c("uid plan_id company_id party_id starts_on ends_on rides_used price_paid currency status"), (),
             {P: None, O: None, PA: None}, create=False, update=False, group="passes",
             actions=(Action("cancel", {"status": "CANCELLED"}, {"status": ["PENDING"]}, portals=(PA, P)),)),
    Resource("shuttle-pass", M_SUBS, "sales.shuttle_pass", c("subscription_id pass_no medium nfc_card_id status"), (),
             {P: None, O: None, PA: None}, create=False, update=False, group="passes",
             actions=(Action("revoke", {"status": "REVOKED"}, {"status": ["ACTIVE"]}, portals=(P,)),)),
    Resource("nfc-card", M_SUBS, "sales.nfc_card", c("party_id wallet_id status issued_at"), c("party_id wallet_id"),
             {P: "shuttle.manage", PA: None}, readonly_portals=(PA,), create=False, group="passes",
             actions=(Action("block", {"status": "BLOCKED"}, {"status": ["ACTIVE"]}),
                      Action("unblock", {"status": "ACTIVE"}, {"status": ["BLOCKED"]}, portals=(P,)),
                      Action("report-lost", {"status": "LOST"}, {"status": ["ACTIVE", "BLOCKED"]}))),
]
