"""Shipping and the integrated network (study 9): catalog, accounts, operations, delivery, partner integration."""
from ._base import Action, P, O, PA, Resource, c, retire, suspend, resume

M = "cargo"
CAT = {P: "shipping.manage", O: None}           # platform catalogs, readable by carriers
OPS = {P: "shipping.manage", O: "shipping.operate"}

RESOURCES = [
    # ------------------------------------------------------------- catalog and zones (9.21)
    Resource("service-product", M, "ship.service_product",
             c("code name cutoff_time guaranteed max_weight_kg network_model status"),
             c("code name cutoff_time guaranteed max_weight_kg max_dims_cm network_model"), CAT, readonly_portals=(O,),
             group="catalog", actions=(retire(),)),
    Resource("service-option", M, "ship.service_option", c("code name applicable_services surcharge_id"),
             c("code name applicable_services surcharge_id"), CAT, readonly_portals=(O,), group="catalog"),
    Resource("surcharge", M, "ship.surcharge_definition", c("code name calc_method value currency valid"),
             c("code name trigger_rule calc_method value currency valid"), CAT, readonly_portals=(O,), group="catalog"),
    Resource("geo-zone", M, "ship.geo_zone", c("country_code governorate city_id district zone_class servicing_hub_id"),
             c("country_code governorate city_id district polygon zone_class servicing_hub_id delivery_days"), CAT,
             readonly_portals=(O,), group="catalog"),
    Resource("price-zone", M, "ship.pricing_zone_chart", c("origin_zone_id dest_zone_id price_zone valid"),
             c("origin_zone_id dest_zone_id price_zone valid"), CAT, readonly_portals=(O,), delete=True,
             order="origin_zone_id, dest_zone_id", group="catalog"),
    Resource("transit-time", M, "ship.transit_time_matrix", c("origin_zone_id dest_zone_id service_id transit_days delivery_by_time"),
             c("origin_zone_id dest_zone_id service_id transit_days delivery_by_time"), CAT, readonly_portals=(O,),
             delete=True, order="origin_zone_id, dest_zone_id", group="catalog"),
    Resource("rate-table", M, "ship.rate_table", c("company_id service_id currency valid status"),
             c("company_id service_id currency valid"), OPS, company_col="company_id", group="rates",
             actions=(Action("publish", {"status": "PUBLISHED"}, {"status": ["DRAFT"]}), retire(("PUBLISHED",)))),
    Resource("rate-entry", M, "ship.rate_table_entry", c("rate_table_id price_zone weight_break price per_kg_over min_charge"),
             c("rate_table_id price_zone weight_break price per_kg_over min_charge"), OPS, delete=True,
             order="rate_table_id, price_zone, weight_break", group="rates"),
    Resource("fuel-surcharge", M, "ship.fuel_surcharge_index", c("period diesel_price_ref pct published_at"),
             c("period diesel_price_ref pct"), CAT, readonly_portals=(O,), group="rates"),
    Resource("hold-rate-card", M, "ship.cargo_rate_card",
             c("company_id route_id service_id weight_from_kg weight_to_kg volume_to_m3 price currency valid"),
             c("company_id route_id service_id weight_from_kg weight_to_kg volume_to_m3 price currency valid"), OPS,
             company_col="company_id", delete=True, group="rates"),
    Resource("prohibited-item", M, "ship.prohibited_item", c("code name hs_prefix rule country_code"),
             c("code name hs_prefix rule country_code"), {P: "shipping.manage", O: None, PA: None},
             readonly_portals=(O, PA), delete=True, group="catalog"),
    Resource("routing-rule", M, "ship.routing_rule",
             c("company_id service_id origin_zone_id dest_zone_id preferred_modes cutoff_time transit_days priority"),
             c("company_id service_id origin_zone_id dest_zone_id preferred_modes cutoff_time transit_days priority"), OPS,
             company_col="company_id", delete=True, group="network"),

    # ------------------------------------------------------------- network (9.9)
    Resource("hub", M, "ship.hub", c("station_id company_id sort_capacity status"), c("station_id company_id sort_capacity hours"),
             OPS, company_col="company_id", group="network", actions=(suspend(), resume())),
    Resource("sort-window", M, "ship.sort_window", c("hub_id direction starts_at ends_at cutoff"),
             c("hub_id direction starts_at ends_at cutoff"), CAT, delete=True, group="network"),
    Resource("linehaul", M, "ship.linehaul_schedule",
             c("origin_hub_id dest_hub_id departure_time arrival_time days mode carrier_company_id capacity_kg status"),
             c("origin_hub_id dest_hub_id departure_time arrival_time days mode carrier_company_id capacity_kg"), OPS,
             company_col="carrier_company_id", group="network", actions=(suspend(), resume(), retire(("ACTIVE", "SUSPENDED")))),
    Resource("access-point", M, "ship.access_point",
             c("station_id partner_party_id point_type capacity hold_days commission_bp status"),
             c("station_id partner_party_id point_type capacity hours services hold_days commission_bp"), CAT,
             readonly_portals=(O,), group="network", actions=(suspend(), resume())),
    Resource("locker", M, "ship.locker_compartment", c("access_point_id code size shipment_id status"),
             c("access_point_id code size"), CAT, readonly_portals=(O,), group="network"),

    # ------------------------------------------------------------- accounts
    Resource("address", M, "ship.address", c("party_id address_text landmark short_code geo_zone_id verified"),
             c("party_id geo_zone_id lat lng address_text landmark short_code"), {P: "shipping.manage", O: "shipping.operate", PA: None},
             owner_col="party_id", group="accounts", actions=(Action("verify", {"verified": True}, {}, portals=(P, O)),)),
    Resource("shipper-account", M, "ship.shipper_account",
             c("account_no party_id company_id account_type credit_limit billing_cycle status"),
             c("account_no party_id company_id account_type credit_limit billing_cycle wallet_id pricing_agreement_id"), OPS,
             company_col="company_id", group="accounts",
             actions=(Action("hold", {"status": "ON_HOLD"}, {"status": ["ACTIVE"]}),
                      Action("release", {"status": "ACTIVE"}, {"status": ["ON_HOLD", "PENDING"]}),
                      Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE", "ON_HOLD"]}))),
    Resource("pricing-agreement", M, "ship.pricing_agreement", c("company_id account_id min_charge_override valid status"),
             c("company_id account_id discounts earned_tiers min_charge_override valid"), OPS, company_col="company_id",
             group="accounts"),

    # ------------------------------------------------------------- shipments and operations (9.4, 9.9)
    Resource("shipment", M, "ship.shipment",
             c("tracking_no company_id shipper_party_id service_id origin_station_id dest_station_id declared_value "
               "cod_amount currency billable_weight_kg cargo_category committed_delivery_at status created_at"),
             (), {P: None, O: None, PA: None}, create=False, update=False, filters=c("status tracking_no"),
             group="shipments"),
    Resource("parcel", M, "ship.parcel", c("shipment_id piece_no label_no weight_kg content_desc fragile"), (),
             {P: None, O: None, PA: None}, create=False, update=False, order="shipment_id, piece_no", group="shipments"),
    Resource("shipment-leg", M, "ship.shipment_leg",
             c("shipment_id contract_id seq mode carrier_company_id trip_id load_id courier_route_id from_station_id to_station_id price status"),
             c("shipment_id seq mode carrier_company_id trip_id load_id courier_route_id from_station_id to_station_id from_seq to_seq price"),
             OPS, group="shipments",
             actions=(Action("book", {"status": "BOOKED"}, {"status": ["PLANNED"]}),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PLANNED", "BOOKED"]}))),
    Resource("tracking-event", M, "ship.tracking_event",
             c("shipment_id unit_id load_id leg_id milestone reason_code station_id ts"), (),
             {P: None, O: None, PA: None}, create=False, update=False, order="ts DESC", group="shipments"),
    Resource("handling-unit", M, "ship.handling_unit", c("label_no unit_type parent_unit_id seal_no current_station_id status"),
             c("label_no unit_type parent_unit_id seal_no current_station_id"), OPS, company_col="company_id",
             group="operations",
             actions=(Action("close", {"status": "CLOSED"}, {"status": ["OPEN"]}),
                      Action("reopen", {"status": "OPENED"}, {"status": ["CLOSED", "ARRIVED"]}))),
    Resource("unit-item", M, "ship.handling_unit_item", c("unit_id shipment_id parcel_id added_at removed_at"),
             c("unit_id shipment_id parcel_id"), OPS, group="operations",
             actions=(Action("remove", {}, {}, stamp="removed_at"),)),
    Resource("load", M, "ship.load",
             c("uid trip_id vehicle_id truck_combination_id load_type origin_hub_id dest_hub_id max_weight_kg used_weight_kg seal_no status"),
             c("trip_id vehicle_id truck_combination_id load_type origin_hub_id dest_hub_id max_weight_kg max_volume_m3 pallet_positions"),
             OPS, company_col="company_id", group="operations",
             actions=(Action("start-loading", {"status": "LOADING"}, {"status": ["PLANNED"]}),
                      Action("seal", {"status": "SEALED"}, {"status": ["LOADING"]}),
                      Action("depart", {"status": "IN_TRANSIT"}, {"status": ["SEALED"]}),
                      Action("arrive", {"status": "ARRIVED"}, {"status": ["IN_TRANSIT"]}),
                      Action("close", {"status": "CLOSED"}, {"status": ["ARRIVED"]}))),
    Resource("load-stop", M, "ship.load_stop", c("load_id seq station_id planned_at actual_at"),
             c("load_id seq station_id planned_at actual_at"), OPS, delete=True, order="load_id, seq", group="operations"),
    Resource("load-plan", M, "ship.load_plan", c("load_id handling_unit_id stop_seq position"),
             c("load_id handling_unit_id stop_seq position"), OPS, delete=True, order="load_id, stop_seq", group="operations"),
    Resource("cargo-capacity", M, "ship.trip_cargo_capacity",
             c("trip_id max_weight_kg max_volume_m3 max_items used_weight_kg used_items"),
             c("trip_id max_weight_kg max_volume_m3 max_items"), OPS, order="trip_id DESC", group="operations"),
    Resource("capacity-booking", M, "ship.capacity_booking",
             c("load_id trip_id route_id seller_company_id buyer_company_id reserved_weight_kg rate currency status"),
             c("load_id trip_id route_id seller_company_id reserved_weight_kg reserved_volume_m3 positions rate currency"),
             OPS, company_col="buyer_company_id", group="operations",
             actions=(Action("confirm", {"status": "CONFIRMED"}, {"status": ["REQUESTED"]}),
                      Action("release", {"status": "RELEASED"}, {"status": ["CONFIRMED"]}),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["REQUESTED", "CONFIRMED"]}))),
    Resource("courier-route", M, "ship.courier_route", c("route_date hub_id courier_user_id vehicle_id status"),
             c("route_date hub_id courier_user_id vehicle_id"), OPS, company_col="company_id", group="couriers",
             actions=(Action("start", {"status": "IN_PROGRESS"}, {"status": ["PLANNED"]}),
                      Action("complete", {"status": "COMPLETED"}, {"status": ["IN_PROGRESS"]}),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["PLANNED"]}))),
    Resource("pickup-request", M, "ship.pickup_request",
             c("shipper_party_id address_id pickup_window pieces courier_route_id status created_at"),
             c("shipper_party_id address_id pickup_window pieces courier_route_id"), OPS, company_col="company_id",
             group="couriers",
             actions=(Action("assign", {"status": "ASSIGNED"}, {"status": ["REQUESTED"]}),
                      Action("picked-up", {"status": "PICKED_UP"}, {"status": ["ASSIGNED"]}),
                      Action("fail", {"status": "FAILED"}, {"status": ["ASSIGNED"]}),
                      Action("cancel", {"status": "CANCELLED"}, {"status": ["REQUESTED", "ASSIGNED"]}))),
    Resource("courier-stop", M, "ship.courier_assignment",
             c("courier_route_id stop_seq kind shipment_id pickup_request_id eta status"),
             c("courier_route_id stop_seq kind shipment_id pickup_request_id eta"), OPS, order="courier_route_id, stop_seq",
             group="couriers",
             actions=(Action("done", {"status": "DONE"}, {"status": ["PENDING"]}),
                      Action("fail", {"status": "FAILED"}, {"status": ["PENDING"]}),
                      Action("skip", {"status": "SKIPPED"}, {"status": ["PENDING"]}))),

    # ------------------------------------------------------------- delivery and claims
    Resource("delivery-attempt", M, "ship.delivery_attempt", c("shipment_id attempt_no result reason_code responsible ts"), (),
             {P: None, O: None, PA: None}, create=False, update=False, order="ts DESC", group="delivery"),
    Resource("delivery-proof", M, "ship.delivery_proof", c("shipment_id method delivered_to ts"), (),
             {P: None, O: None, PA: None}, create=False, update=False, order="ts DESC", group="delivery"),
    Resource("delivery-preference", M, "ship.delivery_preference", c("shipment_id party_id pref_type value fee status"),
             c("shipment_id party_id pref_type value"), {P: None, O: "shipping.operate", PA: None}, owner_col=None,
             group="delivery",
             actions=(Action("apply", {"status": "APPLIED"}, {"status": ["REQUESTED"]}, portals=(P, O)),
                      Action("reject", {"status": "REJECTED"}, {"status": ["REQUESTED"]}, portals=(P, O)))),
    Resource("cod", M, "ship.cod_collection", c("shipment_id amount currency collected_at status"), (),
             {P: None, O: None, PA: None}, create=False, update=False, group="delivery",
             actions=(Action("mark-remitted", {"status": "REMITTED"}, {"status": ["COLLECTED"]}, portals=(O, P)),)),
    Resource("weight-audit", M, "ship.weight_audit", c("parcel_id measured_weight_kg delta_kg adjustment_amount dispute_status ts"),
             c("parcel_id measured_weight_kg measured_dims_cm delta_kg adjustment_amount"), OPS, group="delivery",
             actions=(Action("accept-dispute", {"dispute_status": "ACCEPTED"}, {"dispute_status": ["OPEN"]}),
                      Action("reject-dispute", {"dispute_status": "REJECTED"}, {"dispute_status": ["OPEN"]}))),
    Resource("guarantee-claim", M, "ship.guarantee_claim",
             c("shipment_id committed_at delivered_at eligible exclusion_reason refund_amount status"), (),
             {P: "shipping.manage", O: None, PA: None}, create=False, update=False, readonly_portals=(O, PA), group="delivery",
             actions=(Action("approve", {"status": "APPROVED", "eligible": True}, {"status": ["OPEN"]}),
                      Action("reject", {"status": "REJECTED", "eligible": False}, {"status": ["OPEN"]}))),
    Resource("return", M, "ship.return_authorization", c("original_shipment_id merchant_account_id reason return_shipment_id status"),
             c("original_shipment_id merchant_account_id reason"), {P: None, O: "shipping.operate", PA: None}, group="delivery",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["REQUESTED"]}, portals=(P, O)),
                      Action("reject", {"status": "REJECTED"}, {"status": ["REQUESTED"]}, portals=(P, O)),
                      Action("received", {"status": "RECEIVED"}, {"status": ["APPROVED", "IN_TRANSIT"]}, portals=(P, O)))),
    Resource("cargo-claim", M, "ship.cargo_claim", c("shipment_id claim_type amount currency liable_leg_id status created_at"),
             c("shipment_id claim_type amount currency"), {P: "shipping.manage", O: "shipping.operate", PA: None}, group="delivery",
             actions=(Action("review", {"status": "UNDER_REVIEW"}, {"status": ["OPEN"]}, portals=(P, O)),
                      Action("approve", {"status": "APPROVED"}, {"status": ["UNDER_REVIEW"]}, portals=(P,)),
                      Action("reject", {"status": "REJECTED"}, {"status": ["OPEN", "UNDER_REVIEW"]}, portals=(P,)))),
    Resource("scorecard", M, "ship.carrier_scorecard",
             c("carrier_company_id access_point_id period otd_pct fadr_pct scan_pct damage_pct loss_pct score"),
             c("carrier_company_id access_point_id period otd_pct fadr_pct scan_pct damage_pct loss_pct score"),
             {P: "shipping.manage", O: None}, readonly_portals=(O,), group="delivery"),

    # ------------------------------------------------------------- partner integration (9.25)
    Resource("integration-partner", M, "ship.integration_partner", c("party_id name partner_type protocol api_client_id status"),
             c("party_id name partner_type protocol api_client_id"), {P: "shipping.manage"}, group="partners",
             actions=(Action("go-live", {"status": "ACTIVE"}, {"status": ["SANDBOX"]}), suspend(), resume(),
                      Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED", "SANDBOX"]}))),
    Resource("partner-agreement", M, "ship.partner_contract", c("partner_id roles services territory exclusive liability_cap currency valid status"),
             c("partner_id roles services territory exclusive sla fees liability_cap currency valid"), {P: "shipping.manage"},
             group="partners", actions=(Action("activate", {"status": "ACTIVE"}, {"status": ["DRAFT"]}), retire(to="ENDED", name="end"))),
    Resource("shipment-reference", M, "ship.shipment_reference",
             c("shipment_id parcel_id ref_type issuer_party_id value pushed_to_issuer_at"),
             c("shipment_id parcel_id ref_type issuer_party_id value normalized_value"), {P: "shipping.manage", O: "shipping.operate"},
             filters=c("normalized_value"), group="partners"),
    Resource("status-map", M, "ship.partner_status_map", c("partner_id direction external_code external_reason milestone reason_code version"),
             c("partner_id direction external_code external_reason milestone reason_code version"), {P: "shipping.manage"},
             delete=True, order="partner_id, direction, external_code", group="partners"),
    Resource("pre-alert", M, "ship.partner_pre_alert", c("partner_id manifest_no flight_or_trip_ref expected_at item_count status"), (),
             {P: "shipping.manage"}, create=False, update=False, group="partners",
             actions=(Action("processed", {"status": "PROCESSED"}, {"status": ["RECEIVED", "PARTIAL"]}),
                      Action("close", {"status": "CLOSED"}, {"status": ["PROCESSED", "PARTIAL"]}))),
    Resource("partner-command", M, "ship.partner_command", c("partner_id shipment_id command_type idempotency_key status applied_at"), (),
             {P: "shipping.manage"}, create=False, update=False, group="partners",
             actions=(Action("apply", {"status": "APPLIED"}, {"status": ["RECEIVED"]}, stamp="applied_at"),
                      Action("reject", {"status": "REJECTED"}, {"status": ["RECEIVED"]}))),
    Resource("integration-message", M, "ship.integration_message",
             c("partner_id direction message_type shipment_id status attempts next_retry_at error_code created_at"), (),
             {P: "shipping.manage"}, create=False, update=False, filters=c("status"), group="partners",
             actions=(Action("retry", {"status": "PENDING"}, {"status": ["FAILED", "DEAD_LETTER"]}),)),
    Resource("partner-reconciliation", M, "ship.partner_reconciliation",
             c("partner_id recon_date matched missing_in_platform missing_in_partner amount_diff status"), (),
             {P: "shipping.manage"}, create=False, update=False, group="partners",
             actions=(Action("resolve", {"status": "RESOLVED"}, {"status": ["DISCREPANCY", "OPEN"]}),)),
    Resource("ship-partner-settlement", M, "ship.partner_settlement",
             c("partner_id period service_fees collected_on_behalf claims net_amount currency status"),
             c("partner_id period service_fees collected_on_behalf claims net_amount currency fx_rate"), {P: "shipping.manage"},
             group="partners", actions=(Action("approve", {"status": "APPROVED"}, {"status": ["DRAFT"]}),
                                        Action("paid", {"status": "PAID"}, {"status": ["APPROVED"]}))),
]
