"""Rail (phase 10), taxi (11), car rental (12), passenger transit (13), contracted transport (14) and tracking and
stations (7)."""
from ._base import Action, D, P, O, PA, Resource, activate, c, retire, suspend

RESOURCES = [
    # ------------------------------------------------------------- rail
    Resource("fare-class", "rail", "rail.fare_class", c("company_id code name cabin_rank refundable changeable status"),
             c("code name cabin_rank refundable changeable"), {P: "rail.manage", O: "rail.manage"}, company_col="company_id",
             group="rail", actions=(retire(),)),
    Resource("coach-layout", "rail", "rail.coach_layout", c("company_id code coach_type seat_layout_id berths fare_class_id status"),
             c("code coach_type seat_layout_id berths fare_class_id"), {P: "rail.manage", O: "rail.manage"}, company_col="company_id",
             group="rail", actions=(retire(),)),
    Resource("train-composition", "rail", "rail.train_composition", c("trip_id position coach_no coach_layout_id"),
             c("trip_id position coach_no coach_layout_id"), {P: "rail.manage", O: "rail.manage"}, delete=True,
             order="trip_id DESC, position", group="rail"),
    Resource("journey", "rail", "rail.journey", c("uid party_id origin_station_id dest_station_id status created_at"), (),
             {P: None, O: None, PA: None}, create=False, update=False, group="rail"),
    Resource("journey-leg", "rail", "rail.journey_leg", c("journey_id seq ticket_id trip_id min_connection_min"), (),
             {P: None, O: None, PA: None}, create=False, update=False, order="journey_id DESC, seq", group="rail"),

    # ------------------------------------------------------------- taxi
    Resource("taxi-office", "taxi", "taxi.taxi_office", c("company_id city_id license_no status"), c("company_id city_id license_no"),
             {P: "taxi.manage", O: None}, readonly_portals=(O,), group="taxi",
             actions=(activate(("PENDING", "SUSPENDED")), suspend(), Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("taxi-permit", "taxi", "taxi.taxi_permit", c("permit_no vehicle_id company_id office_id city_id scope gps_required valid status"),
             c("permit_no vehicle_id company_id office_id city_id scope gps_required valid"), {P: "taxi.manage", O: None},
             readonly_portals=(O,), group="taxi",
             actions=(activate(("PENDING", "SUSPENDED")), suspend(), Action("revoke", {"status": "REVOKED"}, {"status": ["PENDING", "ACTIVE", "SUSPENDED"]}))),
    Resource("meter-tariff", "taxi", "taxi.meter_tariff",
             c("city_id version flag_fall per_km per_wait_min night_factor min_fare currency valid status"),
             c("city_id version flag_fall per_km per_wait_min night_factor min_fare currency valid"), {P: "taxi.manage", O: None, PA: None},
             readonly_portals=(O, PA), group="taxi",
             actions=(Action("approve", {"status": "APPROVED"}, {"status": ["DRAFT"]}, by="approved_by"),
                      Action("publish", {"status": "ACTIVE"}, {"status": ["APPROVED"]}), retire(("ACTIVE", "APPROVED")))),
    Resource("taxi-shift", "taxi", "taxi.taxi_shift", c("permit_id vehicle_id driver_party_id period status"),
             c("permit_id vehicle_id driver_party_id period"), {P: None, O: "taxi.operate"}, readonly_portals=(P,), group="taxi",
             actions=(Action("pause", {"status": "PAUSED"}, {"status": ["ON"]}), Action("resume", {"status": "ON"}, {"status": ["PAUSED"]}),
                      Action("end", {"status": "ENDED"}, {"status": ["ON", "PAUSED"]}))),
    Resource("ride-request", "taxi", "taxi.ride_request",
             c("uid rider_user_id kind city_id pickup_text dropoff_text requested_for seats fare_estimate currency status created_at"), (),
             {P: None, O: None, PA: None}, create=False, update=False, group="taxi"),
    Resource("dispatch-offer", "taxi", "taxi.dispatch_offer", c("request_id shift_id distance_m offered_at expires_at response responded_at"), (),
             {P: None, O: None}, create=False, update=False, order="offered_at DESC", group="taxi"),
    Resource("taxi-ride", "taxi", "taxi.ride",
             c("uid request_id shift_id rider_user_id fare_mode started_at ended_at distance_km wait_min fare currency payment_method status"), (),
             {P: None, O: None, PA: None}, create=False, update=False, group="taxi"),

    # ------------------------------------------------------------- car rental
    Resource("rental-company", "car_rental", "rent.rental_company", c("company_id brand status"), c("company_id brand"),
             {P: "rental.manage", O: None, PA: None}, readonly_portals=(O, PA), order="company_id", group="setup",
             actions=(activate(("PENDING", "SUSPENDED")), suspend(), Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("rental-branch", "car_rental", "rent.rental_branch", c("company_id station_id branch_type status"),
             c("station_id branch_type hours"), {P: "rental.manage", O: "rental.operate", PA: None}, company_col="company_id",
             readonly_portals=(PA,), group="setup", actions=(Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE"]}),
                                                             Action("open", {"status": "ACTIVE"}, {"status": ["CLOSED"]}))),
    Resource("rental-class", "car_rental", "rent.rental_vehicle_class", c("code name sort"), c("code name sort"),
             {P: "rental.manage", O: None, PA: None}, readonly_portals=(O, PA), order="sort", group="setup"),
    Resource("rental-car", "car_rental", "rent.rental_fleet", c("vehicle_id company_id rental_class home_branch_id status"),
             c("vehicle_id rental_class home_branch_id"), {P: "rental.manage", O: "rental.operate"}, company_col="company_id",
             order="vehicle_id DESC", group="fleet",
             actions=(Action("maintenance", {"status": "MAINTENANCE"}, {"status": ["AVAILABLE"]}),
                      Action("available", {"status": "AVAILABLE"}, {"status": ["MAINTENANCE"]}), retire(("AVAILABLE", "MAINTENANCE")))),
    Resource("rental-rate", "car_rental", "rent.rental_rate",
             c("company_id rental_class branch_id unit price km_included_per_day extra_km_price deposit_amount currency valid status"),
             c("rental_class branch_id unit price km_included_per_day extra_km_price deposit_amount currency valid"),
             {P: "rental.manage", O: "rental.operate", PA: None}, company_col="company_id", readonly_portals=(PA,), group="pricing",
             actions=(retire(),)),
    Resource("rental-addon", "car_rental", "rent.rental_addon", c("company_id code price unit currency active"),
             c("code price unit currency active"), {P: "rental.manage", O: "rental.operate", PA: None}, company_col="company_id",
             readonly_portals=(PA,), group="pricing"),
    Resource("renter-rule", "car_rental", "rent.renter_rule",
             c("renter_kind rental_class min_age min_license_years docs_required version status"),
             c("renter_kind rental_class min_age min_license_years docs_required version"), {P: "rental.manage", O: None, PA: None},
             readonly_portals=(O, PA), group="setup",
             actions=(Action("approve", {"status": "ACTIVE"}, {"status": ["DRAFT"]}, by="approved_by"), retire())),
    Resource("rental-booking", "car_rental", "rent.rental_booking",
             c("uid company_id renter_party_id rental_class vehicle_id pickup_branch_id return_branch_id period quoted_total currency status created_at"),
             (), {P: None, O: "rental.operate", PA: None}, create=False, update=False, group="bookings",
             actions=(Action("no-show", {"status": "NO_SHOW"}, {"status": ["CONFIRMED"]}, portals=(O,)),)),
    Resource("rental-contract", "car_rental", "rent.rental_contract",
             c("contract_no booking_id vehicle_id signed_at closed_at final_amount status"), (),
             {P: None, O: "rental.operate", PA: None}, create=False, update=False, group="bookings",
             actions=(Action("dispute", {"status": "DISPUTED"}, {"status": ["CLOSED"]}, portals=(PA, O)),)),
    Resource("contract-driver", "car_rental", "rent.contract_driver", c("contract_id party_id is_primary license_verified"),
             c("contract_id party_id is_primary license_verified"), {P: None, O: "rental.operate"}, readonly_portals=(P,),
             order="contract_id DESC", group="bookings"),
    Resource("rental-inspection", "car_rental", "rent.rental_inspection",
             c("contract_id stage odometer_km fuel_level_pct renter_confirmed ts"), (),
             {P: None, O: "rental.operate", PA: None}, create=False, update=False, order="ts DESC", group="bookings",
             actions=(Action("confirm", {"renter_confirmed": True}, {"renter_confirmed": [False]}, portals=(PA,)),)),
    Resource("deposit-hold", "car_rental", "rent.deposit_hold", c("contract_id method amount captured_amount currency status"), (),
             {P: None, O: "rental.operate", PA: None}, create=False, update=False, group="bookings"),
    Resource("telematics-device", "car_rental", "rent.telematics_device", c("company_id vehicle_id provider installed_at status"),
             c("vehicle_id provider installed_at"), {P: "rental.manage", O: "rental.operate"}, company_col="company_id", create=False,
             group="fleet",
             actions=(Action("offline", {"status": "OFFLINE"}, {"status": ["ACTIVE"]}), Action("online", {"status": "ACTIVE"}, {"status": ["OFFLINE"]}),
                      Action("remove", {"status": "REMOVED"}, {"status": ["ACTIVE", "OFFLINE"]}))),
    Resource("vehicle-trip-log", "car_rental", "rent.vehicle_trip_log",
             c("device_id vehicle_id contract_id started_at ended_at distance_km max_speed_kmh geofence_violations"), (),
             {P: "rental.manage", O: "rental.operate"}, create=False, update=False, order="started_at DESC", group="fleet"),

    # ------------------------------------------------------------- passenger transit (13)
    Resource("corridor", "transit_passengers", "net.corridor", c("code name country_code buffer_m status"),
             c("code name country_code path buffer_m"), {P: "transit.manage", O: None}, readonly_portals=(O,), group="transit",
             actions=(activate(("DRAFT",)), retire())),
    Resource("rest-stop", "transit_passengers", "net.approved_rest_stop", c("corridor_id station_id max_minutes"),
             c("corridor_id station_id max_minutes"), {P: "transit.manage", O: None}, readonly_portals=(O,), delete=True,
             order="corridor_id, station_id", group="transit"),
    Resource("crossing-plan", "transit_passengers", "ops.trip_crossing_plan", c("trip_id seq exit_station_id entry_station_id planned_at"),
             c("trip_id seq exit_station_id entry_station_id planned_at"), {P: "transit.manage", O: "transit.operate"}, delete=True,
             order="trip_id DESC, seq", group="transit"),
    Resource("crossing-event", "transit_passengers", "ops.crossing_event", c("trip_id station_id direction source occurred_at lat lng"),
             c("trip_id station_id direction source occurred_at lat lng"), {P: "transit.manage", O: "transit.operate", D: None},
             creator_col="recorded_by_user_id", update=False, order="occurred_at DESC", group="transit"),
    Resource("transit-reconciliation", "transit_passengers", "ops.transit_reconciliation",
             c("trip_id entry_count exit_count missing_ticket_ids status resolved_at note"), c("note"),
             {P: "transit.manage", O: "transit.operate"}, create=False, order="trip_id DESC", group="transit",
             actions=(Action("resolve", {"status": "RESOLVED"}, {"status": ["DISCREPANCY", "OPEN"]}, stamp="resolved_at",
                             by="resolved_by_user_id", portals=(P,)),)),

    # ------------------------------------------------------------- contracted transport (14)
    Resource("service-contract", "contract_transport", "ctr.service_contract",
             c("uid kind client_party_id client_company_id carrier_company_id starts_on ends_on pricing_mode price currency status"),
             c("kind client_party_id client_company_id carrier_company_id starts_on ends_on pricing_mode price currency terms"),
             {P: "contracts.manage", O: "contracts.operate"}, company_col="carrier_company_id", group="contracts",
             actions=(activate(("DRAFT", "SUSPENDED")), suspend(), Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "SUSPENDED"]}))),
    Resource("contract-route", "contract_transport", "ctr.contract_route",
             c("contract_id route_id direction operating_days depart_time vehicle_id driver_party_id attendant_party_id"),
             c("contract_id route_id direction operating_days depart_time vehicle_id driver_party_id attendant_party_id"),
             {P: "contracts.manage", O: "contracts.operate"}, delete=True, group="contracts"),
    Resource("contract-rider", "contract_transport", "ctr.contract_rider",
             c("contract_id passenger_party_id guardian_party_id pickup_station_id dropoff_station_id guardian_consent_at status"),
             c("contract_id passenger_party_id guardian_party_id pickup_station_id dropoff_station_id guardian_consent_at"),
             {P: "contracts.manage", O: "contracts.operate"}, group="riders",
             actions=(Action("pause", {"status": "PAUSED"}, {"status": ["ACTIVE"]}), Action("resume", {"status": "ACTIVE"}, {"status": ["PAUSED"]}),
                      Action("end", {"status": "ENDED"}, {"status": ["ACTIVE", "PAUSED"]}))),
    Resource("authorized-receiver", "contract_transport", "ctr.authorized_receiver", c("rider_id party_id relation verified_at"),
             c("rider_id party_id relation"), {P: "contracts.manage", O: "contracts.operate"}, delete=True, order="rider_id DESC",
             group="riders", actions=(Action("verify", {}, {}, stamp="verified_at"),)),
    Resource("attendance", "contract_transport", "ctr.attendance_event",
             c("trip_id rider_id event received_by_party_id occurred_at source"),
             c("trip_id rider_id event received_by_party_id occurred_at lat lng source"),
             {P: "contracts.manage", O: "contracts.operate", D: None}, update=False, order="occurred_at DESC", group="riders"),
    Resource("contract-invoice", "contract_transport", "ctr.contract_invoice", c("contract_id period_start period_end amount currency status"),
             c("contract_id period_start period_end amount currency"), {P: "contracts.manage", O: "contracts.operate"}, group="contracts",
             actions=(Action("issue", {"status": "ISSUED"}, {"status": ["DRAFT"]}), Action("paid", {"status": "PAID"}, {"status": ["ISSUED"]}),
                      Action("void", {"status": "VOID"}, {"status": ["DRAFT", "ISSUED"]}))),

    # ------------------------------------------------------------- tracking and stations (7)
    Resource("station-gate", "tracking_stations", "net.station_gate", c("station_id code gate_type status"),
             c("station_id code gate_type"), {P: "stations.operate", O: None}, readonly_portals=(O,), group="stations",
             actions=(Action("close", {"status": "CLOSED"}, {"status": ["ACTIVE"]}), Action("open", {"status": "ACTIVE"}, {"status": ["CLOSED"]}))),
    Resource("station-display", "tracking_stations", "net.station_display", c("station_id gate_id device_serial kind last_seen_at status"),
             c("station_id gate_id device_serial kind"), {P: "stations.operate"}, group="stations", actions=(retire(("ACTIVE", "OFFLINE")),)),
    Resource("trip-delay", "tracking_stations", "ops.trip_delay", c("trip_id stop_seq delay_min cause source reported_at"),
             c("trip_id stop_seq delay_min cause source"), {P: "stations.operate", O: "stations.operate", D: None}, update=False,
             order="reported_at DESC", group="tracking"),
    Resource("tracking-state", "tracking_stations", "ops.tracking_state", c("trip_id driver_user_id last_ping_at status off_reason level updated_at"),
             (), {P: None, O: None}, create=False, update=False, order="updated_at DESC", group="tracking"),
    Resource("driver-notice", "tracking_stations", "ops.driver_notice", c("user_id trip_id body created_at ack_at"),
             c("user_id trip_id body"), {P: "tracking.all", O: "tracking.own", D: None}, readonly_portals=(D,), update=False,
             order="created_at DESC", group="tracking", actions=(Action("acknowledge", {}, {"ack_at": [None]}, stamp="ack_at", portals=(D,)),)),
    Resource("vehicle-service-status", "tracking_stations", "fleet.vehicle_service_status",
             c("vehicle_id status reason incident_id period created_at"), c("vehicle_id status reason incident_id period"),
             {P: None, O: "incident.manage"}, company_col="company_id", readonly_portals=(P,), update=False, group="continuity"),
    Resource("insurance-claim", "tracking_stations", "fleet.insurance_claim",
             c("incident_id policy_id insurer_ref amount currency status last_sync_at"),
             c("incident_id policy_id insurer_ref amount currency"), {P: None, O: "incident.manage"}, company_col="company_id",
             readonly_portals=(P,), group="continuity",
             actions=(Action("under-review", {"status": "UNDER_REVIEW"}, {"status": ["NOTIFIED"]}),
                      Action("accepted", {"status": "ACCEPTED"}, {"status": ["UNDER_REVIEW"]}),
                      Action("rejected", {"status": "REJECTED"}, {"status": ["UNDER_REVIEW"]}),
                      Action("paid", {"status": "PAID"}, {"status": ["ACCEPTED"]}), Action("close", {"status": "CLOSED"}, {"status": ["PAID", "REJECTED"]}))),
    Resource("boarding-validator", "tracking_stations", "fleet.boarding_validator",
             c("device_serial vehicle_id validator_type firmware deny_list_version last_sync_at status"),
             c("device_serial vehicle_id validator_type firmware"), {P: None, O: "vehicle.manage"}, company_col="company_id",
             readonly_portals=(P,), group="continuity", actions=(retire(("ACTIVE", "OFFLINE")),)),
    Resource("driving-hours", "tracking_stations", "fleet.driving_hours_log", c("party_id trip_id kind started_at ended_at source"),
             c("party_id trip_id kind started_at ended_at source"), {P: None, O: "trip.assign_crew"}, company_col="company_id",
             readonly_portals=(P,), order="started_at DESC", group="continuity"),
]
