# Use case and data flow model of Masslak, derived from the Analysis and Design Study v2.5 (English edition).
# Section numbers in "ref" point to that study.

# ---------------------------------------------------------------- actors
ACTORS = [
    # id, name, kind, description, study ref
    ("visitor", "Visitor", "Primary", "Unregistered user who browses and compares scheduled trips", "3.1 a"),
    ("passenger", "Passenger", "Primary", "Registered customer who books scheduled trips, pays from the wallet and boards with a QR ticket", "3.1 d, 7.1"),
    ("daily", "Shuttle passenger", "Primary", "Daily rider of shuttle lines who boards by scanning the vehicle sticker and pays station by station", "3.1 e, 7.3 a, 7.13"),
    ("owner", "Carrier account owner", "Primary", "Owner of a transport company or individual vehicle owner; controls the company's users, fleet and finances", "3.3, 3.4"),
    ("scheduler", "Trip scheduler", "Primary", "Carrier employee who creates and launches trips and assigns crews", "3.3"),
    ("accountant", "Company accountant", "Primary", "Carrier employee who follows receivables, settlements and withdrawals", "3.3"),
    ("driver", "Driver / host", "Primary", "Crew member who runs the assigned trip from the driver app: tracking, boarding scans, stops, cash, SOS", "3.3, 7.3, 7.8"),
    ("shipper", "Shipper / store", "Primary", "Sender of parcels or consignments, including stores and importers", "3.1 h, 9.14"),
    ("recipient", "Recipient", "Primary", "Receiver of a shipment who controls delivery options from the tracking link", "9.16"),
    ("hub", "Courier company / hub operator", "Primary", "Operator of a courier company, station or sorting hub that receives, sorts and loads shipments", "9.6, 9.18"),
    ("courier", "Courier", "Primary", "Field courier who picks up and delivers shipments with proof of delivery", "9.17"),
    ("apoint", "Access point operator", "Primary", "Shop, locker, fuel station or rest stop acting as a drop-off and pickup point", "9.15"),
    ("fuel", "Fuel station attendant", "Primary", "Employee of a contracted fuel station who records refueling paid through the platform", "14.11"),
    ("reststop", "Rest stop / merchant", "Primary", "Contracted rest stop, restaurant or merchant accepting payment and points through the platform", "14.12, 14.13"),
    ("loyalty", "Loyalty partner", "Primary", "Partner that funds or redeems points (airlines, retailers, other programs)", "5.13"),
    ("agency", "Travel agency / sub-agent", "Primary", "Intermediary booking through the agent portal within its quota and deposit", "14.9"),
    ("corporate", "Corporate client", "Primary", "Company booking travel for its staff at contract rates", "14.3"),
    ("affiliate", "Marketing affiliate", "Primary", "Partner referring customers through links for a referral commission", "14.3"),
    ("admin", "Platform administrator", "Primary", "Platform staff who approve companies and partners and manage reference data and policies", "3.1 f"),
    ("finance", "Platform finance", "Primary", "Staff in charge of bank reconciliation, settlements, payouts and refund approval", "3.3, 6.3"),
    ("support", "Support employee", "Primary", "Staff who handle complaints, claims and inquiries and decide compensation", "7.6"),
    ("marketing", "Marketing manager", "Primary", "Staff who define campaigns and offers within an approved budget", "5.12"),
    ("dpo", "Data Protection Officer", "Primary", "Reviews processing, consents, impact assessments and data incidents", "16.13"),
    ("aisup", "AI assistant supervisor", "Primary", "Maintains the assistant's knowledge and monitors conversations", "7.10"),
    ("compliance", "Compliance officer", "Primary", "Manages authority policies and adapters, official requests and security logs", "3.3, 8"),
    ("authority", "Authority employee", "Primary", "Employee of a security, customs or crossing authority acting within its scope", "3.1 j, 8"),
    ("regulator", "Regulator", "Primary", "Reads the governance, tracking and alerts dashboard and sets delegated policies", "2.4, 2.5"),
    ("inspector", "Inspector", "Primary", "Field officer or authorized body checking tickets, vehicles and licenses", "7.3 c, 32.8"),
    ("verifier", "Document verifier", "Primary", "Anyone checking a printed booking or ticket on the public verification page", "16.25"),
    ("acctofficer", "Accounting integration officer", "Primary", "Maintains journal entries, mappings and synchronization with accounting systems", "3.3, 13"),
    # secondary and system actors
    ("gateway", "Payment gateway / bank", "Secondary (system)", "Card gateways, wallet providers and the bank holding customer funds", "6.3, 6.4, 6.7"),
    ("secauth", "Security & government authorities", "Secondary (system)", "Authorities connected through the Security & Compliance Hub (screening, orders, requests)", "8"),
    ("border", "Border systems", "Secondary (system)", "Crossing and customs systems exchanging manifest messages", "11"),
    ("govlic", "Government licensing systems", "Secondary (system)", "Sources that confirm vehicle and driver license validity", "4.18, 3.8"),
    ("tax", "Tax authority", "Secondary (system)", "E-invoicing platform receiving invoices in clearance or reporting mode", "13.11"),
    ("erp", "Accounting / ERP system", "Secondary (system)", "External accounting systems receiving journal entries and invoices", "13.5, 13.12"),
    ("crm", "CRM help desk", "Secondary (system)", "Off-the-shelf help desk synchronized with cases by signed webhooks", "7.6 d"),
    ("global", "Global courier company", "Secondary (system)", "Partner such as FedEx, DHL, UPS or Aramex exchanging orders and updates by API", "9.22"),
    ("ota", "Intermediary platform (OTA / GDS)", "Secondary (system)", "Aggregators and distribution systems searching and booking through the channel API", "14.2, 14.4"),
    ("notify", "Notification providers", "Secondary (system)", "SMS, push and e-mail services delivering notifications", "34"),
    ("gate", "Boarding gate device", "Secondary (device)", "QR/NFC validator at the bus door, working offline", "7.3 a"),
]
ACTOR = {a[0]: a for a in ACTORS}

# ---------------------------------------------------------------- use case diagrams
# Each case: (id, name, phase); assoc: (actor, case); include: (base, included); extend: (extension, base)
UC = []

UC.append(dict(
    id="UC-1", title="Scheduled trip booking", boundary="Masslak: scheduled intercity travel",
    primary=["visitor", "passenger"], secondary=["gateway", "secauth"],
    gen=[("passenger", "visitor")],
    cases=[("1.1", "Search and compare trips", 1), ("1.2", "View trip details and seat map", 1),
           ("1.3", "Register and verify identity (KYC)", 1), ("1.4", "Book a trip", 1),
           ("1.5", "Hold seats", 1), ("1.6", "Enter passenger data", 1), ("1.7", "Screen passengers", 1),
           ("1.8", "Pay for the booking", 1), ("1.9", "Redeem points", 1), ("1.10", "Top up the wallet", 1),
           ("1.11", "Show ticket and rotating QR", 1), ("1.12", "Cancel and get a refund", 1),
           ("1.13", "Rate the trip", 1), ("1.14", "Submit a complaint or claim", 1)],
    assoc=[("visitor", "1.1"), ("visitor", "1.2"), ("visitor", "1.3"), ("passenger", "1.4"), ("passenger", "1.10"),
           ("passenger", "1.11"), ("passenger", "1.12"), ("passenger", "1.13"), ("passenger", "1.14"),
           ("1.7", "secauth"), ("1.8", "gateway"), ("1.10", "gateway")],
    include=[("1.4", "1.5"), ("1.4", "1.6"), ("1.4", "1.7"), ("1.4", "1.8")],
    extend=[("1.9", "1.8")],
    details={
        "1.1": ("Search by origin, destination, date and passengers; compare carriers, times, prices, ratings and on-time rates", "7.1, P-01, P-02"),
        "1.2": ("Stops, fare ladder, rest stops, baggage rules and the seat map for the chosen pair", "4.12, P-03"),
        "1.3": ("Create an account and verify identity in the app; limits follow the KYC level", "3.8, 6.3"),
        "1.4": ("Complete booking of one or more seats on a scheduled trip", "7.1"),
        "1.5": ("Temporary seat lock for the chosen segments (10 minutes)", "7.1, 4.12 c"),
        "1.6": ("Names as on the identity document, ID or passport, nationality, mobile", "7.1, 11.9"),
        "1.7": ("Screening request per the authority's policy: ALLOW, REVIEW or DENY", "8.3, 8.4"),
        "1.8": ("Deduction from the wallet or card top-up into escrow with an idempotency key", "6.2, 7.1"),
        "1.9": ("Use loyalty points for a partial or full discount", "5.13 b"),
        "1.10": ("Card or transfer top-up through the payment provider adapter", "6.3"),
        "1.11": ("Signed, short-lived QR shown at boarding", "7.3"),
        "1.12": ("Refund per the fare brand's cancellation rules", "5.9, 6.2"),
        "1.13": ("Rating after completion, feeding the on-time and service score", "7.7"),
        "1.14": ("Case linked to the booking, with SLA by priority", "7.6"),
    }))

UC.append(dict(
    id="UC-2", title="Shuttle transport", boundary="Masslak: shuttle lines",
    primary=["daily", "driver", "inspector"], secondary=["gate", "notify"],
    cases=[("2.1", "Keep location and Bluetooth on", 2), ("2.2", "Board by scanning the vehicle sticker", 2),
           ("2.3", "Board through a QR/NFC gate", 2), ("2.4", "Pay the first segment", 2),
           ("2.5", "Pay for companions", 2), ("2.6", "Refuse boarding: vehicle full", 2),
           ("2.7", "Continue to the next station", 2), ("2.8", "Charge the next segment", 2),
           ("2.9", "Warn of low balance", 2), ("2.10", "Prove alighting with station QR", 2),
           ("2.11", "Detect alighting automatically", 2), ("2.12", "Show the active ticket", 2),
           ("2.13", "Dispute a deduction", 2), ("2.14", "Broadcast the trip presence token", 2),
           ("2.15", "Record a cash fare", 2), ("2.16", "Monitor boardings and capacity", 2)],
    assoc=[("daily", "2.2"), ("daily", "2.3"), ("daily", "2.7"), ("daily", "2.10"), ("daily", "2.12"), ("daily", "2.13"),
           ("driver", "2.14"), ("driver", "2.15"), ("driver", "2.16"), ("inspector", "2.12"),
           ("2.3", "gate"), ("2.9", "notify")],
    include=[("2.2", "2.1"), ("2.2", "2.4"), ("2.3", "2.4"), ("2.7", "2.8"), ("2.7", "2.1"), ("2.11", "2.1")],
    extend=[("2.5", "2.2"), ("2.6", "2.2"), ("2.9", "2.8")],
    details={
        "2.1": ("Location permission at all times and Bluetooth during a ride; otherwise the app locks (SOS stays available)", "7.13 a, b"),
        "2.2": ("Scan the QR on the vehicle; the system identifies vehicle, line and direction and opens a ride", "7.3 a, 7.13 c"),
        "2.3": ("Door validator reads the app code, an NFC phone or a prepaid card; works offline", "7.3 a"),
        "2.4": ("Fare of the first station, the fixed band or the whole line, deducted at boarding", "7.13 c"),
        "2.5": ("Pay for two or more people in one scan", "7.3 d"),
        "2.6": ("At licensed capacity the scan is refused (VEHICLE_FULL) and the driver is alerted", "7.13 c, 4.13"),
        "2.7": ("Presence confirmed by Nearby proximity or moving together when the vehicle leaves a station", "7.13 b, c"),
        "2.8": ("Next segment fare, or the remainder after a fixed band, deducted with a notification", "7.13 c"),
        "2.9": ("Before each station if the balance does not cover the next segment; continuing creates an outstanding amount", "7.13 c"),
        "2.10": ("Scan the station QR to close the ride and get an immediate receipt", "7.13 c"),
        "2.11": ("Both presence signals lost for 90 s and 150 m: the ride closes", "7.13 c"),
        "2.12": ("Animated code that changes every few seconds, verified offline by signature", "7.3 c"),
        "2.13": ("Dispute within 48 hours with proximity log, positions and stop events as evidence", "7.13 c"),
        "2.14": ("Signed BLE token from the driver's phone or a vehicle beacon, rotating every few minutes", "7.13 b"),
        "2.15": ("Cash fare recorded under cash controls", "6.5, 7.3 a"),
        "2.16": ("Instant boarding notifications, passenger counter and capacity alerts", "7.3 b"),
    }))

UC.append(dict(
    id="UC-3", title="Carrier operations", boundary="Masslak: carrier (operator) portal",
    primary=["owner", "scheduler", "accountant"], secondary=["admin", "govlic"],
    cases=[("3.1", "Register the company", 1), ("3.2", "Review and approve the company", 1),
           ("3.3", "Manage users and roles", 1), ("3.4", "Manage fleet and licenses", 1),
           ("3.5", "Verify licenses", 1), ("3.6", "Manage drivers and hosts", 1),
           ("3.7", "Define routes, stations and fares", 1), ("3.8", "Schedule trips", 1),
           ("3.9", "Check trip completeness", 1), ("3.10", "Publish trips", 1), ("3.11", "Assign vehicle and crew", 1),
           ("3.12", "View the passenger manifest", 1), ("3.13", "Reschedule or cancel a trip", 1),
           ("3.14", "View sales and account statement", 1), ("3.15", "Set payout schedule and withdraw", 1),
           ("3.16", "Manage subscription and seats", 1)],
    assoc=[("owner", "3.1"), ("owner", "3.3"), ("owner", "3.4"), ("owner", "3.6"), ("owner", "3.7"), ("owner", "3.16"),
           ("scheduler", "3.8"), ("scheduler", "3.10"), ("scheduler", "3.11"), ("scheduler", "3.12"), ("scheduler", "3.13"),
           ("accountant", "3.14"), ("accountant", "3.15"), ("3.2", "admin"), ("3.5", "govlic")],
    include=[("3.1", "3.2"), ("3.4", "3.5"), ("3.8", "3.9"), ("3.10", "3.9")],
    extend=[],
    details={
        "3.1": ("Company or individual account with documents and transport license", "3.4 a, 7.2"),
        "3.2": ("Administration review before the company can sell", "7.2"),
        "3.3": ("Invite users and set roles from the permission catalog; seats per agreement", "3.4 b, c"),
        "3.4": ("Vehicles with chassis, plate, seats, ownership and license expiry dates", "4.3, 4.13, 4.17"),
        "3.5": ("Locked entry with government update and field verification", "4.18"),
        "3.6": ("Driver and host profiles and license classes", "4.3"),
        "3.7": ("Lines with stations, rest stops and the fare ladder within the approved tariff", "4.12, 4.15"),
        "3.8": ("Trip patterns (e.g. daily at 08:00) generating dated trips and trip numbers", "4.16, 7.2"),
        "3.9": ("Licensed vehicle, valid driver, pricing in place and no conflict", "7.2"),
        "3.10": ("Trips appear to the public and to channels", "7.2"),
        "3.11": ("No overlapping vehicle or crew assignments", "4.3"),
        "3.12": ("Passenger list generated from tickets, sent to authorities when required", "7.3, 8"),
        "3.13": ("Passengers are notified; refunds and compensation follow the policy", "7.9"),
        "3.14": ("Sales, settlements and payable balances", "6.6"),
        "3.15": ("Payout frequency within the policy; settle cash owed first", "6.5, 6.6"),
        "3.16": ("Package, agreement, commission and billing", "5.10"),
    }))

UC.append(dict(
    id="UC-4", title="Driver app", boundary="Masslak: driver app (operator portal)",
    primary=["driver"], secondary=["secauth", "fuel"],
    cases=[("4.1", "Open the assigned trip", 1), ("4.2", "Keep location on", 1), ("4.3", "Share live location", 1),
           ("4.4", "View the passenger list", 1), ("4.5", "Scan boarding codes", 1),
           ("4.6", "Record arrival and departure at stops", 1), ("4.7", "Sell a ticket for cash", 1),
           ("4.8", "Raise SOS", 1), ("4.9", "Receive an authority order", 5), ("4.10", "Report an incident", 1),
           ("4.11", "Pay for fuel with the virtual fuel card", 1)],
    assoc=[("driver", "4.1"), ("driver", "4.4"), ("driver", "4.5"), ("driver", "4.6"), ("driver", "4.7"),
           ("driver", "4.8"), ("driver", "4.10"), ("driver", "4.11"), ("4.9", "secauth"), ("4.8", "secauth"),
           ("4.11", "fuel")],
    include=[("4.1", "4.2"), ("4.1", "4.3"), ("4.5", "4.2"), ("4.6", "4.2")],
    extend=[("4.9", "4.3")],
    details={
        "4.1": ("Only trips assigned to the driver; the app locks if location is off", "7.13 a, D-01"),
        "4.2": ("Continuous location permission; switching it off raises an immediate alert", "7.13 a, 7.8"),
        "4.3": ("Position about every 15 seconds; silence thresholds escalate to the company", "7.8"),
        "4.4": ("Manifest with seats, names and boarding status", "7.3"),
        "4.5": ("Verify the signed rotating QR, offline with later synchronization", "7.3"),
        "4.6": ("Stop events with delay; departure closes sales from that stop", "4.12 f"),
        "4.7": ("Cash sale on the company's trips under cash controls", "6.5"),
        "4.8": ("Emergency alert to the company and the authorities", "8.4"),
        "4.9": ("Stop, divert or inspect orders received through the hub", "8.2, 8.4"),
        "4.10": ("Incident with evidence, vehicle suspension and continuity decision", "7.12"),
        "4.11": ("Rotating QR with company caps, matched to the station radius", "14.11 b, c"),
    }))

UC.append(dict(
    id="UC-5", title="Shipping and logistics", boundary="Masslak: integrated shipping",
    primary=["shipper", "recipient", "apoint"], secondary=["hub", "courier", "global", "gateway"],
    cases=[("5.1", "Create a shipment and get a quote", 3), ("5.2", "Pay or choose COD", 3),
           ("5.3", "Drop off at an access point", 3), ("5.4", "Accept and weigh at the station", 3),
           ("5.5", "Sort and consolidate handling units", 3), ("5.6", "Load on a linehaul leg", 3),
           ("5.7", "Track the shipment", 3), ("5.8", "Manage delivery options", 3),
           ("5.9", "Deliver with proof of delivery", 3), ("5.10", "Record a failed attempt", 3),
           ("5.11", "Collect from a pickup point or locker", 3), ("5.12", "Return to sender", 3),
           ("5.13", "Settle fares and remit COD", 3), ("5.14", "Exchange orders and updates by API", 3),
           ("5.15", "File a shipping claim", 3)],
    assoc=[("shipper", "5.1"), ("shipper", "5.7"), ("shipper", "5.15"), ("recipient", "5.7"), ("recipient", "5.8"),
           ("recipient", "5.11"), ("apoint", "5.3"), ("apoint", "5.11"), ("5.4", "hub"), ("5.5", "hub"), ("5.6", "hub"),
           ("5.9", "courier"), ("5.12", "hub"), ("5.14", "global"), ("5.2", "gateway"), ("5.13", "gateway")],
    include=[("5.1", "5.2")],
    extend=[("5.10", "5.9"), ("5.12", "5.10")],
    details={
        "5.1": ("Origin, destination, parties, contents, weight and declared value; billable-weight pricing", "9.2, 9.13"),
        "5.2": ("Wallet payment into escrow, or cash on delivery", "9.2, 9.3"),
        "5.3": ("Prepaid label dropped at a shop, locker, fuel station or rest stop", "9.15"),
        "5.4": ("Actual weight, prohibited items screening, QR label and tracking number", "9.2"),
        "5.5": ("Scan on arrival, next destination, consolidation, missort detection", "9.6"),
        "5.6": ("Bus hold, truck load or courier leg chosen by the routing engine", "9.6, 9.7"),
        "5.7": ("Unified tracking across legs, platform and external references", "9.8, 9.23"),
        "5.8": ("Reschedule, redirect, change address, hold, prepay COD, authorize a person", "9.16"),
        "5.9": ("Signature level from photo to adult signature with ID; location radius check", "9.17 b"),
        "5.10": ("Reason code and recipient options; up to three attempts", "9.17 c"),
        "5.11": ("Pickup with OTP or ID within the holding period", "9.15"),
        "5.12": ("Return after the last attempt or holding period, at the return charge", "9.17 c, 9.19"),
        "5.13": ("Fare released to the company minus commission; COD to the sender's wallet", "9.2"),
        "5.14": ("Pre-alerts, creation orders and status updates with global partners", "9.22 b, 9.24"),
        "5.15": ("Loss or damage claim within the liability limit", "9.19"),
    }))

UC.append(dict(
    id="UC-6", title="Service partners and loyalty", boundary="Masslak: partners and rewards",
    primary=["owner", "passenger", "loyalty"], secondary=["fuel", "reststop"],
    cases=[("6.1", "Set fuel limits per vehicle and driver", 1), ("6.2", "Record a refueling", 1),
           ("6.3", "Verify fuel card and location", 1), ("6.4", "Pre-order at a rest stop", 1),
           ("6.5", "Pay at a rest stop by QR", 1), ("6.6", "Redeem points", 1), ("6.7", "Earn points", 1),
           ("6.8", "Transfer points to a partner program", 1), ("6.9", "View partner sales and settlements", 1),
           ("6.10", "Rate a rest stop", 1)],
    assoc=[("owner", "6.1"), ("passenger", "6.4"), ("passenger", "6.5"), ("passenger", "6.7"), ("passenger", "6.8"),
           ("passenger", "6.10"), ("loyalty", "6.8"), ("6.2", "fuel"), ("6.5", "reststop"), ("6.9", "fuel"),
           ("6.9", "reststop"), ("loyalty", "6.9")],
    include=[("6.2", "6.3")],
    extend=[("6.6", "6.5")],
    details={
        "6.1": ("Caps per vehicle, driver and day, fuel type and optional prior approval", "14.11 b"),
        "6.2": ("Quantity, unit price, amount, vehicle, driver and trip; no cash between driver and station", "14.11"),
        "6.3": ("Rotating fuel QR and vehicle location within the station radius", "14.11 b, c"),
        "6.4": ("Menu and offers before or during the trip, ready at the short stop", "14.12 b"),
        "6.5": ("Payment QR from the wallet, points or both, with an electronic receipt", "14.12 b"),
        "6.6": ("Points redeemed at rest stops, for trips, upgrades or rewards", "5.13 b"),
        "6.7": ("Points after trip completion and on partner purchases", "5.13 a"),
        "6.8": ("Conversion to airline or other programs with consent and limits", "5.13 b"),
        "6.9": ("Partner sales, commission and periodic settlement", "14.11, 14.12 c"),
        "6.10": ("Cleanliness, prices and speed of service ratings", "14.12 d"),
    }))

UC.append(dict(
    id="UC-7", title="Administration, finance and support", boundary="Masslak: platform administration (web)",
    primary=["admin", "finance", "support", "marketing", "dpo", "aisup"], secondary=["gateway", "crm"],
    cases=[("7.1", "Approve carriers and partners", 1), ("7.2", "Manage central stations and reference data", 1),
           ("7.3", "Configure policies and tariffs", 1), ("7.4", "Handle a case", 1), ("7.5", "Decide compensation", 1),
           ("7.6", "Approve compensation payment", 1), ("7.7", "Reconcile bank and wallets daily", 1),
           ("7.8", "Execute carrier payouts", 1), ("7.9", "Run marketing campaigns", 1),
           ("7.10", "Review processing and consents", 1), ("7.11", "Supervise the AI assistant", 1),
           ("7.12", "Synchronize cases with the CRM", 1)],
    assoc=[("admin", "7.1"), ("admin", "7.2"), ("admin", "7.3"), ("support", "7.4"), ("finance", "7.6"),
           ("finance", "7.7"), ("finance", "7.8"), ("marketing", "7.9"), ("dpo", "7.10"), ("aisup", "7.11"),
           ("7.7", "gateway"), ("7.8", "gateway"), ("7.12", "crm")],
    include=[("7.4", "7.5"), ("7.4", "7.12")],
    extend=[("7.6", "7.5")],
    details={
        "7.1": ("Company, partner and point onboarding and status changes", "7.2, 14.11"),
        "7.2": ("Station register, cities, countries and codes", "4.11, 12.1"),
        "7.3": ("Policy authority matrix, approved tariffs, fare brands, fees", "2.5, 4.15, 5"),
        "7.4": ("Complaints, claims and inquiries in one thread with internal notes", "7.6 b"),
        "7.5": ("Resolution, amount within the cap and the responsible party", "7.6 c"),
        "7.6": ("Finance approval with two-factor verification, separate from the decision role", "7.6 c"),
        "7.7": ("Bank balance equals wallet balances plus receivables; differences alert", "6.3, 6.7"),
        "7.8": ("Per schedule and policy, after cash owed is settled", "6.6"),
        "7.9": ("Campaigns and offers within the approved budget", "5.12"),
        "7.10": ("Processing register, consents, DPIA and data incidents", "16.13"),
        "7.11": ("Knowledge, evaluation and conversation monitoring", "7.10"),
        "7.12": ("Signed webhooks to an off-the-shelf help desk", "7.6 d"),
    }))

UC.append(dict(
    id="UC-8", title="Security, compliance and authorities", boundary="Masslak: Security & Compliance Hub",
    primary=["compliance", "authority", "regulator", "inspector", "verifier"], secondary=["secauth", "border"],
    cases=[("8.1", "Configure authority policies and adapters", 1), ("8.2", "Screen passengers, crews and vehicles", 1),
           ("8.3", "Submit manifest and obtain clearance", 6), ("8.4", "Issue an order (ban, stop, divert)", 5),
           ("8.5", "Request official data", 5), ("8.6", "Verify the authority and deliver encrypted data", 5),
           ("8.7", "View the governance dashboard", 1), ("8.8", "Inspect tickets and vehicles in the field", 1),
           ("8.9", "Verify a document's authenticity", 1), ("8.10", "Monitor security events and audit logs", 1),
           ("8.11", "Manage IP and range rules", 1), ("8.12", "Exchange border manifest messages", 6)],
    assoc=[("compliance", "8.1"), ("compliance", "8.10"), ("compliance", "8.11"), ("compliance", "8.6"),
           ("authority", "8.4"), ("authority", "8.5"), ("regulator", "8.7"), ("inspector", "8.8"), ("verifier", "8.9"),
           ("8.2", "secauth"), ("8.3", "secauth"), ("8.12", "border")],
    include=[("8.5", "8.6"), ("8.3", "8.12")],
    extend=[],
    details={
        "8.1": ("Per-authority policy, exchange pattern and adapter configuration", "8.3"),
        "8.2": ("Before booking: passenger, driver, host, vehicle and company", "8.4"),
        "8.3": ("No transition to boarding before approval on lines subject to it", "8.4, 11.3"),
        "8.4": ("Inbound orders applied to trips, vehicles or persons", "8.2"),
        "8.5": ("Request with a reference number within the authority's scope", "8.4"),
        "8.6": ("Authority verification, preparation, encrypted delivery and logging", "8.4, 8.5"),
        "8.7": ("Aggregated indicators without personal data; every view logged", "2.4"),
        "8.8": ("Active ticket and license status checks, offline by signature", "7.3 c, 32.8"),
        "8.9": ("Server-side answer that detects edited printouts", "16.25"),
        "8.10": ("Sign-in and activity logs read through a separate audit connection", "16.6, 16.20"),
        "8.11": ("Block, allow or throttle by IP, range, country or AS number", "16.17"),
        "8.12": ("PRE_MANIFEST, FINAL_MANIFEST, RESPONSE, CROSSING_EVENT, DISCREPANCY", "11.3"),
    }))

UC.append(dict(
    id="UC-9", title="Distribution channels and agencies", boundary="Masslak: distribution and agencies",
    primary=["agency", "corporate", "affiliate", "admin"], secondary=["ota"],
    cases=[("9.1", "Search and book within quota", 9), ("9.2", "Book through the channel API", 9),
           ("9.3", "Manage sub-agents and deposit", 9), ("9.4", "View statement and commissions", 9),
           ("9.5", "Book at corporate contract rates", 9), ("9.6", "Refer customers by link", 9),
           ("9.7", "Configure channel quotas and commission models", 9), ("9.8", "Settle channel commissions", 9)],
    assoc=[("agency", "9.1"), ("agency", "9.3"), ("agency", "9.4"), ("corporate", "9.5"), ("affiliate", "9.6"),
           ("admin", "9.7"), ("9.2", "ota"), ("9.4", "ota"), ("admin", "9.8")],
    include=[("9.1", "9.8"), ("9.2", "9.8")],
    extend=[],
    details={
        "9.1": ("Agent portal with deposit wallet or credit and preferred fares", "14.9"),
        "9.2": ("Availability, pricing and booking with certification and quotas", "14.4, 14.5"),
        "9.3": ("Sub-agents under the agency and their deposits", "14.9"),
        "9.4": ("Account statement and commission lines", "14.6"),
        "9.5": ("Contract rates, possibly with a service fee", "14.3"),
        "9.6": ("Referral commission for affiliates", "14.3"),
        "9.7": ("Commission models by configuration, quotas and look-to-book controls", "14.3, 14.5"),
        "9.8": ("Periodic financial settlement with channels", "14.6"),
    }))

UC.append(dict(
    id="UC-10", title="Accounting and e-invoicing", boundary="Masslak: accounting core and integration hub",
    primary=["passenger", "acctofficer", "finance"], secondary=["tax", "erp", "gateway"],
    cases=[("10.1", "Issue an e-invoice for each transaction", 1), ("10.2", "Finalize and sign the invoice", 1),
           ("10.3", "Submit to the tax authority", 5), ("10.4", "Issue a credit or debit note", 1),
           ("10.5", "Post journal entries from events", 1), ("10.6", "Map accounts and sync to ERP", 1),
           ("10.7", "Reconcile sub-ledger with general ledger", 1), ("10.8", "Manage tax profiles", 1),
           ("10.9", "Produce financial reports", 1)],
    assoc=[("passenger", "10.1"), ("acctofficer", "10.6"), ("acctofficer", "10.5"), ("acctofficer", "10.8"), ("finance", "10.4"),
           ("finance", "10.7"), ("finance", "10.9"), ("10.3", "tax"), ("10.6", "erp"), ("10.7", "gateway")],
    include=[("10.1", "10.2"), ("10.2", "10.3"), ("10.4", "10.3")],
    extend=[],
    details={
        "10.1": ("One or more invoices per booking, shipment, freight contract, subscription or partner service", "13.11 a"),
        "10.2": ("Gapless number, UUID, hash chain, signature, QR, XML and PDF at payment", "13.11 b"),
        "10.3": ("Clearance or reporting mode; responses stored and the invoice fully locked", "13.11 b"),
        "10.4": ("Corrections only through linked documents", "13.11 a"),
        "10.5": ("Posting rules convert module events into balanced entries", "13.4"),
        "10.6": ("Adapters push entries and invoices to accounting systems via API", "13.5, 13.12"),
        "10.7": ("Daily summary entries from the wallet ledger with automatic reconciliation", "13.4"),
        "10.8": ("Seller and buyer tax profiles per country pack", "13.13, 12.4"),
        "10.9": ("Statements and reports for finance and governance", "35"),
    }))

# Overview: actors to subsystems (packages)
SUBSYSTEMS = [("S1", "Scheduled travel", "UC-1"), ("S2", "Shuttle transport", "UC-2"), ("S3", "Carrier operations", "UC-3"),
              ("S4", "Driver app", "UC-4"), ("S5", "Shipping and logistics", "UC-5"), ("S6", "Partners and loyalty", "UC-6"),
              ("S7", "Administration, finance and support", "UC-7"), ("S8", "Security and compliance", "UC-8"),
              ("S9", "Distribution channels", "UC-9"), ("S10", "Accounting and e-invoicing", "UC-10")]

# ---------------------------------------------------------------- data stores
STORES = [
    ("D1", "Identity and access", "app_user, user_session, role, permission, device and location permission state", "Hashed passwords, opaque session tokens, RLS"),
    ("D2", "Parties and documents", "party, company, party_role, document, KYC records, bank_account", "Encrypted document numbers"),
    ("D3", "Fleet and crews", "vehicle, license_record, ownership, crew_profile", "Locked license dates (4.18)"),
    ("D4", "Network and tariffs", "city, station, route, route_stop, approved line, tariff, line_fare_table", "Versioned tariffs"),
    ("D5", "Trips and inventory", "trip, trip_stop, seat_segment, crew_assignment, trip pattern", "Atomic seat locks"),
    ("D6", "Bookings and tickets", "booking, passenger, ticket, boarding_event", "Personal data minimized"),
    ("D7", "Pricing and allocation", "fare_brand, price_snapshot, price_allocation, tax and commission rules", "Snapshot per booking"),
    ("D8", "Wallets and ledger", "wallet, ledger_transaction, ledger_entry, payment, payout, cash_remittance", "Double entry, idempotency keys"),
    ("D9", "Tracking and operations", "trip_position, tracking_state, tracking_alert, stop events, incidents", "7-day position retention"),
    ("D10", "Shuttle rides", "shuttle_ride, ride_segment_charge, proximity_sample, presence_beacon", "7-day proximity retention"),
    ("D11", "Shipments", "shipment, handling unit, tracking event, proof of delivery, access point, partner reference", "Chain of custody"),
    ("D12", "Security and compliance", "screening_request/result, watchlist, manifest_submission, authority_order, data request, sos_event", "Restricted, audited access"),
    ("D13", "Partners and loyalty", "partner, partner_sale, partner_settlement, points account and ledger, reward catalog", "Netting against payables"),
    ("D14", "Invoices and journal", "e-invoice document, journal entry, posting rule, account mapping, sync log", "Immutable once locked"),
    ("D15", "Cases and notifications", "case, case_event, notification log, assistant conversation log", "Internal notes separated"),
    ("D16", "Audit logs", "auth_event, activity_log, data_access_log, row_change, log_seal", "Append-only, sealed"),
    ("D17", "Channels and agencies", "channel, agency, sub-agent, quota, commission model", "API keys per channel"),
]
STORE = {s[0]: s for s in STORES}

# ---------------------------------------------------------------- DFD level 1 processes
PROCESSES = [
    ("1", "Manage identity and access"), ("2", "Manage parties, fleet and network"), ("3", "Schedule trips and inventory"),
    ("4", "Book and ticket"), ("5", "Price, tax and allocate"), ("6", "Manage wallet, payments and settlement"),
    ("7", "Operate trips (boarding and tracking)"), ("8", "Operate shuttle rides"), ("9", "Ship and deliver consignments"),
    ("10", "Security and compliance hub"), ("11", "Partners and loyalty"), ("12", "Accounting and e-invoicing"),
    ("13", "Support, notifications and AI assistant"), ("14", "Distribution channels and agencies"),
]
