# Narrative content for the Use Case and Data Flow Diagrams document (from the study v2.5).

LEVEL1_DESC = {
    "1": ("Registration, sign-in for each portal, sessions, roles and permissions, KYC levels, and the device's location and Bluetooth permission state that the apps require.", "3.4, 3.5, 3.8, 7.13 a, 16.18"),
    "2": ("Onboarding of companies and individuals with documents, vehicles with licenses and ownership, crews, the station register, lines and approved tariffs.", "3.4, 4.2 to 4.4, 4.11, 4.13 to 4.18"),
    "3": ("Trip patterns, generated trips with stops and trip numbers, crew and vehicle assignment, and seat inventory per segment.", "4.12, 4.16, 7.2"),
    "4": ("Search, seat holds, passenger data, screening, pricing, payment, ticket issue with rotating QR, and cancellation with refund.", "7.1, 4.12, 5.9"),
    "5": ("Calculation layers, central or free pricing, fare brands, taxes, fees, commissions and the price allocation tree saved with each booking.", "5.1 to 5.11"),
    "6": ("Wallets, top-up and withdrawal, escrow, release on completion, refunds, cash clearing, carrier payouts and daily reconciliation in a double-entry ledger.", "6.1 to 6.8"),
    "7": ("Driver app tracking, boarding scans, stop events, alerts and escalation, route adherence and trip completion.", "7.3, 7.8, 4.15, 7.12"),
    "8": ("Shuttle boarding by sticker or gate, presence by Nearby proximity and moving together, station-by-station charging, alighting detection and capacity.", "7.3 a, 7.13"),
    "9": ("Shipment creation and pricing, acceptance at stations and access points, routing and sorting, linehaul, last-mile delivery with proof, delivery options, settlement and global partner exchange.", "9.1 to 9.25"),
    "10": ("Screening, manifests and clearance, authority orders, official data requests, SOS and incidents, border manifest messages and governance indicators.", "8, 11, 2.4"),
    "11": ("Contracted fuel stations, rest stops and merchants, loyalty earning and redemption, and partner netting and settlement.", "14.11 to 14.13, 5.13"),
    "12": ("E-invoices for every transaction, submission to the tax authority, posting rules to the general ledger, ERP synchronization and reconciliation.", "13"),
    "13": ("Complaints, claims and inquiries with SLAs, compensation with segregation of duties, notifications, CRM synchronization and the AI assistant.", "7.6, 7.10, 7.11, 34"),
    "14": ("Agencies, sub-agents, corporate clients, affiliates and intermediary platforms booking through the portal or API, with quotas and commission settlement.", "14.1 to 14.10"),
}

LEVEL2_DESC = {
    "DFD-4": [("4.1", "Search trips", "Returns trips between two cities on a date with the pair price, times, carrier and available seats."),
              ("4.2", "Hold seats", "Locks the chosen seats on every segment of the pair for 10 minutes; nothing is half-locked."),
              ("4.3", "Capture passenger data", "Collects names exactly as on the identity document, the document, nationality, date of birth and mobile."),
              ("4.4", "Screen passengers", "Sends the screening request according to the authority's policy and records ALLOW, REVIEW or DENY."),
              ("4.5", "Price the booking", "Applies the calculation layers and fare brand, and saves the price snapshot and allocation lines."),
              ("4.6", "Collect payment", "Requests payment from the wallet into escrow with an idempotency key."),
              ("4.7", "Confirm and issue tickets", "Commits the seats atomically, issues tickets with a rotating QR, notifies, and passes the sale to e-invoicing."),
              ("4.8", "Cancel and refund", "Applies the fare brand's cancellation rules, releases the seats and returns the refundable amount.")],
    "DFD-6": [("6.1", "Top up the wallet", "Card or transfer top-up through the provider adapter; the signed notification is the source of truth."),
              ("6.2", "Hold booking funds in escrow", "Moves the booking amount from the customer's wallet to escrow."),
              ("6.3", "Release funds on completion", "Splits escrow by the allocation lines: carrier net, taxes, platform share and intermediary commissions."),
              ("6.4", "Refund", "Returns refundable amounts from escrow to the customer's wallet."),
              ("6.5", "Clear carrier cash", "Clears cash sold by drivers against the carrier's entitlements and records cash remittances."),
              ("6.6", "Pay out carriers", "Transfers released payables on the carrier's schedule after any cash owed is settled."),
              ("6.7", "Withdraw customer balance", "Pays out to a verified bank account within daily limits."),
              ("6.8", "Reconcile daily", "Checks that the bank balance equals wallet balances plus receivables and alerts on any difference.")],
    "DFD-7": [("7.1", "Track the trip", "Receives the driver's position about every 15 seconds and the location state."),
              ("7.2", "Scan boarding codes", "Verifies the signed rotating QR, offline if needed, and records the boarding event."),
              ("7.3", "Record stop events", "Records arrival and departure with delay; departure closes sales from that stop."),
              ("7.4", "Raise tracking alerts", "Detects silence or tracking off, alerts the driver in the app and by SMS, and escalates to the company."),
              ("7.5", "Complete the trip", "Closes the trip, triggers escrow release and loyalty points.")],
    "DFD-8": [("8.1", "Check location and Bluetooth", "Locks the app when location or the permission is off, or Bluetooth during a ride; SOS stays available."),
              ("8.2", "Open ride at boarding", "Identifies vehicle, line and direction from the sticker, checks capacity and deducts the first fare."),
              ("8.3", "Confirm presence", "Combines Nearby proximity to the signed trip token with moving together with the vehicle."),
              ("8.4", "Charge segment at departure", "When the vehicle leaves a station with the passenger present, deducts the next segment or the remainder."),
              ("8.5", "Warn and record outstanding", "Warns before each station when the balance is short; a continued segment becomes an interest-free outstanding amount."),
              ("8.6", "Close ride on alighting", "Closes the ride on lost presence (90 s, 150 m) or a station QR and sends the receipt."),
              ("8.7", "Track vehicle capacity", "Counts open rides within the licensed capacity and alerts the driver; a full vehicle refuses boarding.")],
    "DFD-9": [("9.1", "Create and price shipment", "Captures parties, contents, weight and value, prices by billable weight and takes payment or COD."),
              ("9.2", "Accept at station or point", "Weighs, screens for prohibited items, labels and starts the chain of custody."),
              ("9.3", "Route and sort", "Chooses the leg by service level, deadline and capacity, and consolidates handling units."),
              ("9.4", "Transport on linehaul", "Records loading and unloading scans on bus, truck or courier legs."),
              ("9.5", "Deliver with proof", "Builds the courier's route and records delivery with the required proof or a failed attempt."),
              ("9.6", "Manage delivery options", "Lets the recipient reschedule, redirect, hold or prepay COD after OTP verification."),
              ("9.7", "Settle fares and COD", "Releases the fare minus commission and transfers COD to the sender's wallet."),
              ("9.8", "Exchange with global partners", "Receives pre-alerts and orders and pushes status updates and proof of delivery by API.")],
    "DFD-10": [("10.1", "Screen persons and vehicles", "Queries the authority before the action and records the result."),
               ("10.2", "Submit manifest, obtain clearance", "Pushes the manifest before departure; lines subject to clearance wait for approval."),
               ("10.3", "Apply authority orders", "Applies ban, stop or divert orders to trips, vehicles or persons and notifies the driver."),
               ("10.4", "Handle official data requests", "Verifies the authority and scope, prepares the record, delivers it encrypted and logs access."),
               ("10.5", "Handle SOS and incidents", "Forwards SOS alerts and incident data with the position."),
               ("10.6", "Exchange border messages", "Sends manifest versions and receives responses, crossing events and discrepancies."),
               ("10.7", "Publish governance indicators", "Aggregates indicators without personal data for the regulator.")],
    "DFD-11": [("11.1", "Authorize fuel purchase", "Checks the rotating fuel QR, the company's caps and that the vehicle is within the station radius."),
               ("11.2", "Record partner sale", "Records fuel, rest stop or merchant sales charged to a wallet or as a receivable."),
               ("11.3", "Earn points", "Credits points after trip completion and on eligible purchases."),
               ("11.4", "Redeem and convert points", "Redeems points at partners or for trips and converts points with partner programs."),
               ("11.5", "Net and settle partners", "Nets partner sales, commissions and redemptions and issues settlement statements.")],
    "DFD-12": [("12.1", "Build draft invoice", "Builds invoice lines from the allocation lines, taxes and tax profiles when the sale is created."),
               ("12.2", "Finalize and sign", "At payment assigns the gapless number and UUID, chains the hash, signs, and generates QR, XML and PDF."),
               ("12.3", "Submit to tax authority", "Submits in clearance or reporting mode and stores the authority's response."),
               ("12.4", "Issue credit or debit note", "Corrects a locked invoice only through a linked note."),
               ("12.5", "Post journal entries", "Converts module events into balanced journal entries through posting rules."),
               ("12.6", "Synchronize with ERP", "Pushes entries and invoices to accounting systems through adapters."),
               ("12.7", "Reconcile sub-ledger", "Reconciles daily wallet summaries with general ledger balances.")],
}

# Fully dressed use case specifications
SPECS = [
    dict(id="UC-1.4", name="Book a trip", primary="Passenger", secondary="Security and government authorities (through the hub); payment gateway (top-up only)",
         pre=["The passenger is signed in and the KYC level allows the amount (3.8, 6.3).",
              "On the mobile app, location permission is granted (7.13 a).",
              "The trip is published and on sale for the chosen pair (4.12)."],
         trigger="The passenger selects a trip from the search results.",
         main=["The system shows the seat map for the boarding and alighting pair.",
               "The passenger selects seats; the system locks them on every segment of the pair for 10 minutes.",
               "The passenger enters each passenger's names exactly as on the identity document, the document, nationality, date of birth and mobile.",
               "The system sends a screening request according to the authority's policy and receives ALLOW.",
               "The system applies the calculation layers and the fare brand, and saves the price snapshot and allocation lines.",
               "The passenger confirms; the system moves the total from the wallet to escrow with an idempotency key.",
               "The system commits the seats atomically, issues tickets with a rotating QR and sends a notification.",
               "The system finalizes and locks the e-invoice for the paid booking."],
         alt=["2a. A seat was just taken: the hold is refused as a whole and the seat map is refreshed.",
              "4a. REVIEW or DENY: the booking does not proceed until resolved according to the authority's policy (8.3).",
              "6a. Insufficient balance: the passenger tops up the wallet (UC-1.10) and continues.",
              "6b. The passenger redeems points for part or all of the fare (UC-1.9).",
              "6c. The hold expired: the passenger chooses seats again."],
         post="Booking confirmed, tickets issued, funds held in escrow, e-invoice finalized.",
         refs="7.1, 4.12 c, 5.1, 5.7, 5.9, 6.2, 8.3, 13.11"),
    dict(id="UC-2.2 / 2.7", name="Ride a shuttle line (station-by-station charging)", primary="Shuttle passenger",
         secondary="Driver / host (presence token), notification providers",
         pre=["Location permission at all times and Bluetooth are on (7.13 a, b).",
              "The balance or subscription covers the first fare and there is no outstanding fare (7.13 c).",
              "The vehicle has not reached its licensed capacity (4.13)."],
         trigger="The passenger scans the QR sticker on the vehicle (or passes a gate).",
         main=["The system identifies the vehicle, line and direction.",
               "The system checks the vehicle's capacity and opens a ride from the boarding station.",
               "The system deducts the fare of the first station, the fixed band or the whole-line fare.",
               "Each time the vehicle leaves a station with the passenger present (Nearby or moving together), the system deducts the next segment or its remainder and notifies the passenger.",
               "The passenger alights: presence is lost for 90 seconds with 150 meters of separation, or the passenger scans the station QR.",
               "The system closes the ride, stops further charges and sends a receipt with the boarding station, alighting point and each segment."],
         alt=["2a. Vehicle full: the scan is refused (VEHICLE_FULL) and the driver is alerted.",
              "4a. The balance does not cover the next segment: the app warns before the station; continuing records an interest-free outstanding amount recovered from the next top-up.",
              "4b. Location or Bluetooth is switched off: the app locks; the rest of the line is charged unless a station QR proves alighting.",
              "5a. The phone shuts down: segments are charged only up to the last departure with confirmed presence and the ride is flagged for review.",
              "6a. The passenger disputes a deduction within 48 hours; the evidence is the proximity log, positions and stop events."],
         post="Ride closed, segment charges posted, capacity counter updated.",
         refs="7.3 a, 7.13 a to c, 4.13, 6.8"),
    dict(id="UC-4.5", name="Scan boarding codes", primary="Driver / host", secondary="Passenger",
         pre=["The trip is assigned to the driver and location is on (7.13 a).",
              "Departure clearance has been obtained on lines subject to it (8.4)."],
         trigger="A passenger presents the rotating QR at boarding.",
         main=["The driver scans the code in the driver app.",
               "The app verifies the digital signature and validity window, offline if needed.",
               "The system records the boarding event and marks the ticket boarded.",
               "The boarding counter and the manifest are updated."],
         alt=["2a. The code was already used, belongs to another trip or is invalid: boarding is refused with the reason.",
              "2b. No connectivity: the scan is stored and synchronized later."],
         post="Boarding recorded; the final manifest is available when boarding closes (11.3).",
         refs="7.3, 8.4, 11.3"),
    dict(id="UC-5.9", name="Deliver with proof of delivery", primary="Courier", secondary="Recipient, shipper",
         pre=["The shipment has arrived and is on the courier's daily route (9.17 a)."],
         trigger="The courier reaches the delivery address.",
         main=["The app shows the required signature level for the shipment.",
               "The courier collects the proof: photo, signature, OTP or ID depending on the level.",
               "The system checks that the courier's location is within the set radius of the address.",
               "If COD applies, the amount is collected or confirmed as prepaid.",
               "The system records the delivery with proof and notifies the shipper and the recipient; a signed proof can be downloaded."],
         alt=["2a. Delivery fails: the courier records a reason code and the recipient receives the control options (9.16); after the last attempt the shipment is held at a pickup point, then returned to the sender.",
              "3a. The location is outside the radius: the scan is rejected or flagged for review.",
              "5a. Offline: scans and proofs are stored and synchronized later with a device timestamp."],
         post="Shipment delivered with proof; settlement and COD transfer can proceed.",
         refs="9.16, 9.17, 9.19, 16.25"),
    dict(id="UC-6.2", name="Record a refueling", primary="Fuel station attendant", secondary="Driver, carrier owner",
         pre=["The station is a contracted partner and the company has set fuel limits (14.11 b)."],
         trigger="The driver presents the virtual fuel card QR at the pump.",
         main=["The attendant scans the code and enters fuel type, quantity and amount.",
               "The system checks the caps and that the vehicle is within the station's radius.",
               "The amount is deducted from the company wallet or recorded as a receivable.",
               "The system records the partner sale with station, vehicle, driver, trip, fuel type, quantity, unit price and amount, and issues a receipt.",
               "Periodically, the system nets fuel receivables against the company's payables and settles the station."],
         alt=["2a. The location does not match: an alert is raised.",
              "2b. A cap is exceeded: the purchase is refused or needs prior approval.",
              "3a. The company's credit limit is exceeded: the service is suspended."],
         post="Partner sale recorded; no cash passed between driver and station.",
         refs="14.11"),
    dict(id="UC-7.4", name="Handle a claim and pay compensation", primary="Support employee", secondary="Platform finance, CRM help desk",
         pre=["A claim is open and linked to a booking; only one open claim per booking (7.6 c)."],
         trigger="A customer submits a claim.",
         main=["The case is categorized and prioritized with its SLA.",
               "The customer, company and support employee correspond in one thread; internal notes stay separate.",
               "The support employee decides the resolution, the amount within the cap, and the responsible party.",
               "Platform finance approves the payment with two-factor verification.",
               "The system posts the compensation from the responsible party's wallet to the customer's wallet once.",
               "The case is resolved and closed, and the events are sent to the CRM by signed webhook."],
         alt=["5a. The responsible party's balance is insufficient: execution is rejected so another party can be chosen or settlement awaited."],
         post="Compensation paid without duplication; the case log is immutable.",
         refs="7.6"),
    dict(id="UC-8.5", name="Request official data", primary="Authority employee", secondary="Compliance officer",
         pre=["The authority is registered with a defined scope (8.3)."],
         trigger="The authority submits a request with a reference number.",
         main=["The system records the request and its reference.",
               "The compliance officer verifies the authority and that the request is within its scope.",
               "The system prepares the requested record (for example the trip record, boardings and GPS route).",
               "The data is delivered encrypted to the authority.",
               "The access is recorded in the security audit log."],
         alt=["2a. The request is outside the authority's scope: it is refused and recorded."],
         post="Official request fulfilled and fully traceable.",
         refs="8.4, 8.5"),
    dict(id="UC-10.1", name="Issue an e-invoice", primary="System (on payment); Passenger as buyer", secondary="Tax authority",
         pre=["A booking, shipment or service has a price allocation (5.7)."],
         trigger="The sale is created (draft) and then paid (final).",
         main=["The system builds a draft invoice from the allocation lines and taxes, without a number or QR.",
               "On payment, the system assigns the gapless number and UUID, chains the hash, signs, and generates the QR, XML and PDF.",
               "The invoice is pushed to the tax authority immediately in clearance mode or within the period in reporting mode.",
               "The authority's response is stored and the invoice is fully locked."],
         alt=["1a. The hold expires without payment: the draft is cancelled and consumes no number.",
              "3a. Before integration is activated: the finalized invoice is final with a local QR and full archiving.",
              "4a. Rejected: the invoice stays stored with the reasons and a corrected linked document is issued.",
              "4b. Accepted with warnings: locked as confirmed and the warnings escalated to finance."],
         post="Locked e-invoice, confirmed by the authority where integration is active.",
         refs="13.11, 13.12"),
]

ASSUMPTIONS = [
    "All content is derived from the Analysis and Design Study v2.5 (English edition); section numbers in the tables refer to that study.",
    "The diagrams show the complete target scope. Use cases of later phases are labelled with their phase; anything without a label belongs to Phase 1.",
    "Notifications are a cross-cutting service (Notification Catalog, Section 34) and appear only where they are part of the use case.",
    "DFD processes describe logical data movement, not the deployment of services; the platform is a modular monolith in the early phases (2.2).",
    "Duplicate symbols (a double border for an external entity, an extra bar for a data store) repeat the same element to keep flows short.",
    "The access matrix (Section 7) is derived from the diagrams, plus a few reads implied by the use cases that are not drawn (for example sign-in reading D1 and the security console reading D16).",
    "Audit logging (D16) is written by every process on each sign-in and state-changing request; to keep the diagrams readable it is drawn only where it is the purpose of the flow.",
]
